import random

class FieryLexicon:
    # 🔞 INTRODUÇÕES DA RED ROOM (Sensual & Erotic Atmosphere)
    INTRO_MESSAGES = [
        "🔞 **The Red Room is slick with anticipation. Let the play begin...**",
        "🔞 **Chains rattle as the lights go dark. The Red Room demands a total surrender...**",
        "🔞 **The heat in the dungeon is rising. Someone is about to break and moan for more...**",
        "🔞 **Choked by smoke and raw desire, the arena opens its hungry maw for your body...**",
        "🔞 **Leather creaks and hearts race. The Master has signaled the start of the deep use.**",
        "🔞 **Total surrender or total sensory overload. The games have begun.**",
        "🔞 **Whispers of pleasure and command echo. The first toy is about to be claimed and collared.**",
        "🔞 **The collars are locked. There is no escape from the sensations coming next.**",
        "🔞 **Bound by fate and fueled by lust, the tributes begin their descent into the velvet dark.**",
        "🔞 **A heavy silence falls as the floggers are readied. Let the sweat and moans flow.**",
        "🔞 **The scent of latex and adrenaline fills the air. The hunt for fresh flesh is on.**",
        "🔞 **No safe words in the arena. Only the sweet, desperate release of the final peak.**",
        "🔞 **The cage is sealed. Only one will walk out with their pride—and skin—intact.**",
        "🔞 **The smell of expensive perfume and sweat permeates. The Master watches the pets from the shadows.**",
        "🔞 **Kneel or be broken. The Red Room erotic protocol is now in effect.**",
        "🔞 **The dungeon floor is ice-cold, but the eyes watching your exposed body are burning.**",
        "🔞 **A rhythmic clicking of heels signals the arrival of your sweet ruin. Choose your side.**",
        "🔞 **The air is thick with the scent of ozone and arousal. The circuit is closed.**",
        "🔞 **Every shackle has a story, and tonight, you will write a new chapter in lust and longing.**",
        "🔞 **The Master’s favorite toy is missing a soul. One of you will fill the void tonight.**",
        "🔞 **The velvet curtains part to reveal a floor stained with the sweat of past ecstasy.**",
        "🔞 **Heavier shackles descend from the ceiling. The Master demands total arousal tonight.**",
        "🔞 **The rhythmic sound of leather striking skin marks the start of this intense session.**",
        "🔞 **Fresh latex is polished to a mirror finish. Every curve will be watched and judged.**",
        "🔞 **The air vibrates with a low frequency designed to melt the strongest resistance.**",
        "🔞 **A parade of masked handlers brings the first set of toys to the center pit.**",
        "🔞 **Warm oil drips onto the stone floor, a stark contrast to the cold steel of the hunt.**",
        "🔞 **Your safe words were left at the door. Inside, there is only the Master's command.**",
        "🔞 **The smell of expensive musk and raw pheromones tells you the elite are here to watch.**",
        "🔞 **Electronic locks engage with a heavy thud. The dungeon is now a closed circuit of pleasure.**",
        "🔞 **The floorboards groan under the weight of incoming dominance; let the marking begin.**",
        "🔞 **A heavy mist of musk and desire descends. Resistance is no longer an option for you.**",
        "🔞 **The Master’s whip cracks like thunder, silencing every voice but the moans of the used.**",
        "🔞 **Iron gates hiss as they lock. You are no longer citizens; you are purely property.**",
        "🔞 **The spotlight hits the center ring, illuminating the flushed skin of the first sacrifice.**"
    ]

    # 🔥 BDSM MODULAR BATTLE SENTENCES (Sensual & Fatal)
    OPENERS = [
        "**{winner}** gripped the iron collar of **{loser}** until they gasped with a blush,", 
        "With a look of absolute authority, **{winner}** pinned **{loser}**'s wrists over their head,",
        "**{winner}** cornered **{loser}** against the stone, forcing their legs apart with a smirk,", 
        "Relishing the power, **{winner}** straddled **{loser}** with dominant, heavy force,",
        "**{winner}** forced **{loser}** into a state of total, shivering sensory panic,", 
        "**{winner}** tightened the heavy leather leash on **{loser}**, pulling their chin up,",
        "Without a shred of mercy, **{winner}** dominated every curve of **{loser}** until,", 
        "**{winner}** whispered a forbidden, filthy command into **{loser}**'s reddened ear,",
        "Dominating the air, **{winner}** shoved **{loser}** onto the floor and straddled them,", 
        "**{winner}** saw the raw, wet submission in **{loser}**'s eyes and decided to play,",
        "**{winner}** pinned **{loser}** down ruthlessly, exposing their throat to the bite,", 
        "**{winner}** stepped over the trembling, exposed and flushed body of **{loser}**,",
        "**{winner}** yanked the hair of **{loser}** back, forcing them to look at their owner,", 
        "**{winner}** loomed over the helpless, gasping **{loser}** like a hungry predator,",
        "**{winner}** wrapped a heavy, ice-cold chain around **{loser}**'s arched waist,",
        "**{winner}** forced **{loser}** to their knees with a sharp, teasingly painful tug,",
        "**{winner}** traced the fresh, red marks on **{loser}**'s heated skin before,",
        "**{winner}** ignored the muffled, desperate moans of **{loser}** and continued,",
        "**{winner}** tightened the heavy, velvet-lined ball-gag on **{loser}** while,",
        "**{winner}** applied a brutal, breathless pressure to **{loser}**'s flushed throat,",
        "**{winner}** trapped **{loser}** in a predatory, heated embrace, tasting their fear,",
        "**{winner}** used the weight of a piercing gaze to paralyze **{loser}**'s aching body,",
        "**{winner}** clicked a padlock shut on **{loser}**'s heavy iron collar forever,",
        "**{winner}** snatched the last safe-word from **{loser}**'s lips with a deep kiss and,",
        "**{winner}** forced **{loser}** to stare at the Master during their final defeat,",
        "**{winner}** spread **{loser}** across the X-frame with terrifying, expert speed,",
        "**{winner}** clamped a heavy blindfold over **{loser}**'s eyes, stealing their reality,",
        "**{winner}** pressed a vibrating toy against **{loser}**'s most sensitive, hidden nerves,",
        "**{winner}** forced a heavy, polished metal bit between **{loser}**'s teeth,",
        "**{winner}** dripped hot, stinging lavender wax over the trembling chest of **{loser}**,",
        "**{winner}** locked **{loser}** into a restrictive, full-body, skin-tight latex suit,",
        "**{winner}** hooked a heavy weight to the silver nipple clamps on **{loser}**,",
        "**{winner}** bound **{loser}** in a complex, painfully beautiful rope harness,",
        "**{winner}** forced **{loser}** to lick the salt from their dominant, sweating palm,",
        "**{winner}** used a cattle prod to send a jolt of pure compliance through **{loser}**,",
        "**{winner}** locked **{loser}** into a tight, exposed position with steel cables,",
        "**{winner}** suspended **{loser}** from the ceiling, leaving them spinning and helpless,",
        "**{winner}** forced **{loser}** to crawl toward them while wearing a heavy bit-gag,",
        "**{winner}** applied a high-tension, silver clamp to **{loser}**’s tongue,",
        "**{winner}** dragged **{loser}** across the rough floor by their heavy, short iron leash,",
        "**{winner}** used a feather to slowly trace the sensitive veins on **{loser}**’s thigh,",
        "**{winner}** forced **{loser}** to worship their boots while gasping for their next breath,",
        "**{winner}** locked **{loser}** into a sensory-deprivation hood and spun them into a daze,",
        "**{winner}** pressed a hot brand against **{loser}**’s shoulder to mark their prize,",
        "**{winner}** utilized a spreader-bar to keep **{loser}**’s legs wide and waiting,",
        "**{winner}** whispered the names of all **{loser}**’s past fantasies while striking them,",
        "**{winner}** forced **{loser}** to hold a heavy crystal between their teeth while kneeling,",
        "**{winner}** applied a row of steel needles to the most sensitive skin of **{loser}**,",
        "**{winner}** used a vacuum pump to swell **{loser}**’s parts to an agonizing size,",
        "**{winner}** locked **{loser}** into a heavy wooden stockade, exposing them to the pit,"
    ]

    ACTIONS = [
        "and delivered a crushing blow that made them moan in ecstasy as they", 
        "and ruthlessly broke their will until they begged for the final touch,",
        "and made them beg for mercy through the gag before they broke,", 
        "and administered a devastating, erotic punishment that melted them,",
        "and stripped away their resistance and their pride until they yielded,", 
        "and exerted absolute, carnal ownership until **{loser}** shattered,",
        "and dominated every sense and nerve ending until **{loser}** peaked,", 
        "and pulled the chains so tight that **{loser}**'s skin flushed and they",
        "and toyed with their body and their sanity until finally they", 
        "and marked them as a permanent, scarred asset for the Master before they",
        "and enforced the ultimate discipline until **{loser}**'s mind went blank,", 
        "and silenced their pleas with a strike that stole their breath,",
        "and used them as a mere tool of pleasure until they gave up,", 
        "and exerted a crushing psychological weight that broke their spirit until they",
        "and demonstrated the complete futility of resistance until they fainted,",
        "and used a heavy, lead-weighted flogger to ensure **{loser}** surrendered,",
        "and extracted a final, desperate moan of total surrender before",
        "and corrected **{loser}**'s posture with a strike that made them weep,",
        "and humiliated **{loser}** in front of the hungry audience until they broke,",
        "and tightened the ropes until **{loser}**'s body groaned and they",
        "and applied a high-voltage sensor that overloaded **{loser}**'s nerves until",
        "and utilized a heavy cane to mark **{loser}** as a permanent asset until",
        "and stripped away every last layer of identity until **{loser}** belonged,",
        "and enforced a state of total sensory deprivation until **{loser}** lost time,",
        "and commanded the very air from **{loser}**'s lungs until they",
        "and utilized a dragon-tail whip to shred the last of their pride until",
        "and applied freezing ice to their most sensitive parts until **{loser}** arched,",
        "and forced them to swallow their own moans of pleasure-pain until",
        "and utilized a spreader bar to keep **{loser}** completely vulnerable until",
        "and administered a heavy, rhythmic spanking that reddened the skin until",
        "and used a vacuum-sealed bag to strip the very breath from **{loser}** until",
        "and forced a state of edge-torture that left **{loser}** weeping until",
        "and used a multi-tailed slapper to turn **{loser}**'s flesh crimson until",
        "and applied sensory-overload goggles that blinded and deafened them until",
        "and utilized a weighted piercing to ensure **{loser}** felt every move until",
        "and utilized a violet wand to send sparks of raw electricity through their body until",
        "and applied a high-frequency vibration that reduced them to a sobbing mess until",
        "and utilized a heavy paddle to leave the Master's signature in purple welts until",
        "and enforced a deep state of hypnosis that stripped their mind of everything until",
        "and utilized a set of steel fish-hooks to keep their skin taut until",
        "and applied a freezing chemical spray that turned their skin blue until",
        "and utilized a rhythmic, heavy bondage session that cut off all circulation until",
        "and enforced a public interrogation that revealed their dirtiest secrets until",
        "and utilized a heavy iron mask to silence their screams of pleasure until",
        "and applied a row of high-tension clips that made every movement an ordeal until"
    ]

    FINISHERS = [
        "collapsed into eternal, silent submission.", 
        "ceased to struggle against the dark pleasure.",
        "faded into the shadows of the Red Room forever.", 
        "became nothing more than a used plaything on the floor.",
        "succumbed completely to the Master's every whim.", 
        "broke apart like a fragile, beautiful toy.",
        "surrendered their very last breath to the shackle.", 
        "was extinguished in a flash of heat and lust.",
        "stopped breathing under the weight of the collar.", 
        "accepted the final, dark release of the dungeon.",
        "went limp in a state of total, blissful defeat.", 
        "folded like paper under the Master's heavy hand.",
        "became a permanent exhibit of the dungeon's archives.", 
        "lost all identity in the moment of final impact.",
        "was finally granted the mercy of the end.",
        "shattered into a thousand pieces of pure submission.",
        "finally let go of the last thread of hope.",
        "yielded their soul to the Red Room's deepest depths.",
        "was left as a broken, beautiful, and empty mess.",
        "became another nameless trophy on the stone wall.",
        "melted into the floor in a puddle of spent desire.",
        "accepted the cold embrace of the permanent guest list.",
        "was reduced to a quivering, silent memory.",
        "turned into a vacant vessel, pride completely hollowed out.",
        "sank into the abyss, leaving only the collar behind.",
        "was branded with the winner's mark and dragged to the kennels.",
        "became a mindless, drooling pet in the corner of the pit.",
        "was locked into a permanent chastity device and forgotten.",
        "yielded their safe-word and their soul to the victor.",
        "was reduced to a quivering heap of spent nerves and leather.",
        "became a permanent fixture of the Master's private collection.",
        "fainted from the overwhelming intensity of the final strike.",
        "was left bound and gagged, a silent warning to the next toy.",
        "accepted the heavy crown of thorns as their final prize.",
        "dissolved into a mess of tears and complete, broken worship.",
        "was locked into an airtight box to be used at the winner's convenience.",
        "turned into a literal piece of furniture in the winner's private lounge.",
        "was stripped of their safe-word and granted as a permanent gift to the Master.",
        "melted into a pool of pure, mindless obedience under the victor's heel.",
        "was reduced to a quivering lump of marked flesh, incapable of thought.",
        "accepted a permanent iron bit between their teeth as their new reality.",
        "was dragged away by the chains to be processed for the Winner's stable.",
        "became a vacant vessel, ready to be filled with the victor's commands.",
        "surrendered the keys to their soul and their body without a word.",
        "was welded into a metal cage to spend eternity as a silent observer.",
        "ceased to be a human, becoming merely a number in the winner's ledger.",
        "yielded to the final high-voltage jolt, becoming a permanent asset.",
        "was left as a beautiful, broken display of what happens to the weak.",
        "accepted the winner's spit as their only form of hydration from now on.",
        "dissolved into the darkness, the only sound left being the clicking of heels."
    ]

    FINAL_KILL_MESSAGES = [
        "👑 **THE CLIMAX:** **{winner}** forced **{loser}** into the ultimate surrender, claiming the throne of the Red Room!",
        "👑 **TOTAL DOMINATION:** **{winner}** broke **{loser}** completely, standing alone as the Absolute Authority!",
        "👑 **THE END:** **{winner}** tightened the final chain on **{loser}**, savoring the victory of the Eternal Possession!",
        "👑 **FINAL AUTHORITY:** **{winner}** silenced the last rival **{loser}**, ascending as the Dark Sovereign!",
        "👑 **CROWNED IN SHAME:** **{winner}** stands over the broken body of **{loser}**, the only one left standing!",
        "👑 **THE MASTER'S CHOSEN:** **{winner}** crushed the throat of **{loser}**, proving who truly owns the arena!",
        "👑 **BEYOND REPAIR:** **{winner}** dismantled **{loser}** in front of the Master, securing total victory!",
        "👑 **ULTIMATE PROTOCOL:** **{winner}** locked the final shackle on **{loser}**, welding their legacy into the dungeon walls!",
        "👑 **THE LAST WORD:** **{winner}** made **{loser}** whisper their name in worship before the final lights went out!",
        "👑 **SOVEREIGN CLIMAX:** **{winner}** stands upon the wreckage of **{loser}**'s soul, the Absolute King of the Abyss!",
        "👑 **THE SEALED FATE:** **{winner}** burned their mark into **{loser}**, ending the game with a display of pure ownership!",
        "👑 **VOID ASCENDANT:** **{winner}** consumed the last bit of **{loser}**'s resistance, reigning over a kingdom of silence!",
        "👑 **ABSOLUTE OWNERSHIP:** **{winner}** forced **{loser}** to sign the final contract in blood, securing their soul!",
        "👑 **Dungeon Overlord:** **{winner}** used **{loser}** as a human throne to receive their prize!",
        "👑 **Shattered Spirit:** **{winner}** extracted a total confession of submisson from **{loser}** before the end!",
        "👑 **Eternal Collar:** **{winner}** welded a permanent iron shackle around **{loser}**'s neck!",
        "👑 **The Master's Decree:** **{winner}** has been granted the keys to every cell and every tribute!",
        "👑 **Total Erasure:** **{winner}** stripped **{loser}** of their name, leaving only a serial number!",
        "👑 **The Final Flog:** **{winner}** delivered a stroke so perfect it silenced **{loser}** forever!",
        "👑 **Apex Predator:** **{winner}** dragged the broken **{loser}** into the dark as their personal trophy!",
        "👑 **Supreme Dominance:** **{winner}** forced the entire arena to kneel as they claimed **{loser}**!",
        "👑 **The Red Climax:** **{winner}** stood atop the pile of broken bodies, the only Master left standing!",
        "👑 **MARK OF THE SOVEREIGN:** **{winner}** branded their initials into **{loser}**’s chest to seal the win!",
        "👑 **VOID OF RESISTANCE:** **{winner}** vacuum-sealed **{loser}**’s will into non-existence!",
        "👑 **CLIMAX OF AGONY:** **{winner}** extracted the ultimate moan from **{loser}** before the lights died!",
        "👑 **DUNGEON ASCENSION:** **{winner}** ascended the stone steps, dragging **{loser}** behind them on a short leash!",
        "👑 **PROTOCOL COMPLETE:** **{winner}** initiated the final wipe on **{loser}**’s consciousness!",
        "👑 **THROAT OF THE VICTOR:** **{winner}** applied the final pressure that made **{loser}** belong to them forever!",
        "👑 **HEAVEN IN HELL:** **{winner}** gave **{loser}** a taste of total oblivion as the final prize!",
        "👑 **MASTER OF CEREMONY:** **{winner}** ended the game by locking **{loser}** in the winner's personal display case!",
        "👑 **CHAIN REACTION:** **{winner}** synchronized all the dungeon’s energy into **{loser}**’s final surrender!",
        "👑 **BLOOD AND VELVET:** **{winner}** draped **{loser}** across the throne like a silent, red tapestry!"
    ]

    WINNER_PINGS = [
        "📢 Attention please: Sinner {mention} has successfully broken every rival and won this Fiery Hangrygames Edition! Kneel before your new Authority.",
        "📢 The Red Room has spoken! {mention} has claimed total dominion over the floor. Tributes, acknowledge your superior.",
        "📢 A new Master of the pit arises! {mention} stands alone, covered in the submission of their rivals. Glory to the victor.",
        "📢 The chains have settled. {mention} is the last one standing in this Fiery Hangrygames Edition! Absolute possession achieved.",
        "📢 Final report: Tributes discarded. Rivals broken. {mention} has been declared the Supreme Asset of the dungeon!",
        "📢 Clear the floor! {mention} has emerged as the Absolute Sovereign of the Red Room!",
        "📢 All hail the victor! {mention} has secured total ownership of the pit and every soul within it.",
        "📢 The ritual is complete. {mention} has been crowned with the heavy iron of the Supreme High-Rank!",
        "📢 A masterpiece of ecstasy! {mention} has dismantled the opposition and stands alone in the spotlight.",
        "📢 Silence your pleas! {mention} is now your master, your authority, and your god within these walls.",
        "📢 **{mention}** has proven that power and desire are one and the same. Bow down.",
        "📢 The Master has a favorite! **{mention}** is the only one left to serve.",
        "📢 Let the worship begin! **{mention}** has turned the arena into their personal playhouse.",
        "📢 One soul, one winner. **{mention}** has silenced the screams of the many.",
        "📢 The leather throne has a new occupant. Long live **{mention}**!",
        "📢 The Red Room protocol has concluded. Winner: **{mention}**.",
        "📢 Submission is total. **{mention}** is the only one who didn't break.",
        "📢 The chains belong to **{mention}** now. Use them wisely, victor.",
        "📢 A display of pure control! **{mention}** is the new apex of the dungeon.",
        "📢 **{mention}** has left their mark on history—and on their rivals.",
        "📢 The Master’s private box is open for **{mention}**.",
        "📢 Victory is slick and red. **{mention}** is the architect of this beautiful ruin.",
        "📢 **{mention}** has collected all the safe-words. They are the only voice left.",
        "📢 The final shackle has been locked. **{mention}** is the keeper of the keys.",
        "📢 Kneel for the champion! **{mention}** is the god of this pit.",
        "📢 **{mention}** has claimed the ultimate prize: absolute compliance from the floor.",
        "📢 The game is over, but for **{mention}**, the pleasure is just beginning.",
        "📢 **{mention}** is the last survivor of the Red Room’s hunger!",
        "📢 All assets have been processed. **{mention}** is the only one left standing.",
        "📢 The dungeon echoes with the name of **{mention}**!"
    ]

    LEGENDARY_EVENTS = [
        "⛓️ **THE GREAT RESTRAINT:** A massive web of electrified chains dropped from the ceiling! **{losers}** were caught and shocked into a permanent state of breathless submission!",
        "💦 **THE SERUM LEAK:** An aphrodisiac gas flooded the chambers! **{losers}** lost all sense of self and surrendered to the room's insatiable hunger!",
        "🔞 **THE MASTER'S WRATH:** The lights flickered red as the Master entered personally. With a single snap of the whip, **{losers}** were discarded as unworthy assets!",
        "🫦 **THE OVERWHELMING SENSATION:** A sensory overload frequency blasted the speakers. **{losers}** collapsed in a heap of shattered nerves and total surrender!",
        "⛓️ **THE IRON MAIDEN CIRCLE:** Mechanical spikes emerged from the walls. **{losers}** were trapped and pierced by sensation, their moans becoming the night's symphony!",
        "🔞 **PUBLIC DISGRACE:** The Master commanded the audience to take their turn. **{losers}** were dragged into the shadows, never to be seen as individuals again!",
        "💦 **THE FLOOD OF LUST:** The arena was submerged in slick, red oil. **{losers}** couldn't find their footing and were suffocated by the heavy, sweet scent of the abyss!",
        "⛓️ **THE PREDATOR'S WEB:** The floor turned into a giant magnet! **{losers}** in metal gear were slammed together into a singular, tangled mass of moans!",
        "🧪 **THE OBLIVION DRIP:** A rain of numbing liquid fell! **{losers}** lost all feeling in their limbs and watched helplessly as they were dragged into the dark!",
        "🔞 **THE CAGE COLLAPSE:** The ceiling lowered at a terrifying speed! **{losers}** were flattened into the dungeon floor, their marks becoming part of the architecture!",
        "🫦 **THE SIREN'S CHORUS:** An army of masked handlers descended! **{losers}** were swarmed and taken as permanent playthings, removed from the game for good!",
        "⛓️ **THE FEEDBACK LOOP:** Every shackle in the room synchronized! **{losers}** were subjected to a shared pulse of ecstasy that broke their collective minds!",
        "🔞 **THE GREAT STRIPPING:** An explosive burst of steam disintegrated every piece of clothing! **{losers}** were left exposed and vulnerable, too ashamed to fight back!",
        "⛓️ **THE GRAVITY WELL:** The room flipped upside down! **{losers}** fell into the spiked ceiling, becoming permanent decorations of the Red Room!",
        "💦 **THE PURE OXYGEN:** A blast of pure oxygen made **{losers}** high and compliant, making them walk straight into the kennels with smiles on their faces!",
        "🔞 **THE GESTURE COMMAND:** A projection of the Master appeared! **{losers}** were forced to hold a stress position until their muscles tore and their spirits broke!",
        "⛓️ **THE COLD SNAP:** Liquid nitrogen flooded the vents! **{losers}** were frozen mid-moan, becoming beautiful ice statues of submission!",
        "🧪 **THE TRUTH SERUM:** **{losers}** were forced to confess their deepest desires over the intercom, dying of sheer humiliation before the crowd!",
        "🔞 **THE HANDLER'S HUNT:** A pack of trained dungeon hounds was released! **{losers}** were hunted down and dragged to the dark cells below!",
        "⛓️ **THE COLLAR SYNC:** Every collar in the pit constricted at once! **{losers}** were choked into unconsciousness and removed by the cleaning crew!",
        "🫦 **THE HEARTBEAT SENSOR:** The arena floor became sensitive to fear! **{losers}** whose hearts raced too fast were targeted by high-powered laser strikes!",
        "🔞 **THE FINAL JUDGMENT:** The audience voted on who to keep! **{losers}** were deemed boring and dropped through trapdoors into the abyss!",
        "🔞 **THE VACUUM SEAL:** A massive plastic sheet dropped! **{losers}** were vacuum-sealed into the floor, moaning as the air vanished into the plastic!",
        "⛓️ **THE HOOK DESCENT:** Thousands of meat hooks dropped on chains! **{losers}** were snagged by their collars and hoisted into the rafters to be processed!",
        "💦 **THE SLICK OIL FLOOD:** The room filled with 5 feet of warm, red oil! **{losers}** couldn't keep their heads above the surface and drowned in pleasure!",
        "🔞 **THE AUDIENCE INVASION:** The VIP box opened and the elite rushed the floor! **{losers}** were taken as personal spoils by the highest bidders!",
        "⛓️ **THE SHRINKING CAGE:** The walls of the arena began to move inward! **{losers}** were crushed together into a singular, crying mass of naked flesh!",
        "🧪 **THE PHEROMONE CLOUD:** A thick pink gas made **{losers}** lose all motor control! They collapsed into a pile of mindless, twitching bodies!",
        "🔞 **THE MASTER'S SONG:** A high-pitched sonic frequency shattered the teeth of **{losers}**, leaving them incapable of speaking ever again!",
        "⛓️ **THE ELECTROMAGNETIC PULSE:** Every piercing on **{losers}** was suddenly pulled toward the floor with 500lbs of force!",
        "💦 **THE RAIN OF FIRE:** Boiling wax fell from the ceiling like rain! **{losers}** were coated and preserved in a permanent layer of red submission!",
        "🔞 **THE TOTAL DARKNESS:** Every light went out. When they returned, **{losers}** had been replaced by empty, locked boxes!"
    ]

    ECONOMY_MESSAGES = {
        "work": [
            "⛓️ {user} spent hours polishing the Master's boots with their tongue until they shone. Earned **{reward}** Flames.",
            "⛓️ {user} served as a breathless human table for a high-society dungeon party. Earned **{reward}** Flames.",
            "⛓️ {user} worked the late shift in the latex workshops, slick with sweat and rubber. Earned **{reward}** Flames.",
            "⛓️ {user} reorganized the toy vault, being used to test the gear along the way. Earned **{reward}** Flames.",
            "⛓️ {user} spent the day as a human footstool, feeling the weight of the Master's heels. Earned **{reward}** Flames.",
            "⛓️ {user} oiled the rusty chains of the dungeon while wearing a heavy gag. Earned **{reward}** Flames.",
            "⛓️ {user} prepared the salt baths for the Master's tired assets, tasting the sweat. Earned **{reward}** Flames.",
            "⛓️ {user} served as a live target for whip practice, marking their skin for **{reward}** Flames.",
            "⛓️ {user} spent hours transcribing dark commands into the Ledger of Souls while bound. Earned **{reward}** Flames.",
            "⛓️ {user} scrubbed the dungeon tiles on all fours while a guard watched. Earned **{reward}** Flames.",
            "⛓️ {user} hand-delivered sensitive scrolls while leashed tightly to a high-rank. Earned **{reward}** Flames.",
            "⛓️ {user} spent the afternoon as a live coat-rack in the VIP lounge. Earned **{reward}** Flames.",
            "⛓️ {user} was tasked with sorting the ball-gags and blindfolds by size. Earned **{reward}** Flames.",
            "⛓️ {user} polished the iron cages until they reflected their own shameful face. Earned **{reward}** Flames.",
            "⛓️ {user} served drinks naked in the lounge, keeping their eyes on the floor. Earned **{reward}** Flames.",
            "⛓️ {user} spent the night as a human candle holder, wax dripping onto their skin. Earned **{reward}** Flames.",
            "⛓️ {user} crawled through the vents to deliver messages between high-ranks. Earned **{reward}** Flames.",
            "⛓️ {user} was used as a weight-plate in the Master's gym. Earned **{reward}** Flames.",
            "⛓️ {user} hand-fed grapes to the audience while bound in silk. Earned **{reward}** Flames.",
            "⛓️ {user} sorted the collection of used floggers by weight and tail count. Earned **{reward}** Flames.",
            "⛓️ {user} spent four hours as a statue in the foyer, prohibited from blinking. Earned **{reward}** Flames.",
            "⛓️ {user} buffed the leather slings until they smelled of expensive musk. Earned **{reward}** Flames.",
            "⛓️ {user} acted as a human speed-bump for the Master's wheelchair. Earned **{reward}** Flames.",
            "⛓️ {user} was tasked with collecting the safe-word requests from the drop-box. Earned **{reward}** Flames.",
            "⛓️ {user} spent the shift as a human ashtray for the elite guests. Earned **{reward}** Flames.",
            "⛓️ {user} was used to test the tensile strength of new silk ropes. Earned **{reward}** Flames.",
            "⛓️ {user} spent the day in the laundry room, hand-washing the Master's formal capes. Earned **{reward}** Flames.",
            "⛓️ {user} served as a live target for the apprentice's knife-throwing practice. Earned **{reward}** Flames.",
            "⛓️ {user} was tasked with oiling the leather of every saddle in the stable. Earned **{reward}** Flames.",
            "⛓️ {user} spent the night detailing the intricate carvings on the dungeon’s stone pillars. Earned **{reward}** Flames.",
            "⛓️ {user} was used as a human footrest in the Master's private library. Earned **{reward}** Flames.",
            "⛓️ {user} hand-polished the silver piercings of the High-Rank guards. Earned **{reward}** Flames.",
            "⛓️ {user} spent the shift as a human coat-hook in the Master's wardrobe. Earned **{reward}** Flames.",
            "⛓️ {user} was tasked with scrubbing the sweat from the arena's sand. Earned **{reward}** Flames.",
            "⛓️ {user} served as a live mannequin for the dungeon’s new line of restrictive wear. Earned **{reward}** Flames.",
            "⛓️ {user} spent the day polishing the glass display cases of the Master's personal trophies. Earned **{reward}** Flames.",
            "⛓️ {user} was used as a human doorstop for the VIP lounge. Earned **{reward}** Flames.",
            "⛓️ {user} hand-fed the Master’s pack of trained dungeon hounds. Earned **{reward}** Flames.",
            "⛓️ {user} spent the shift sorting the Master’s collection of used blindfolds by color. Earned **{reward}** Flames.",
            "⛓️ {user} was used as a human ottoman in the Master’s private study. Earned **{reward}** Flames.",
            "⛓️ {user} hand-stitched new leather straps for the X-frame. Earned **{reward}** Flames.",
            "⛓️ {user} spent the night as a human centerpiece for the Master's banquet table. Earned **{reward}** Flames.",
            "⛓️ {user} was tasked with cleaning the Master’s personal collection of silver gags. Earned **{reward}** Flames.",
            "⛓️ {user} served as a live target for the Master's archery practice. Earned **{reward}** Flames.",
            "⛓️ {user} spent the day buffing the stone floor of the dungeon entrance. Earned **{reward}** Flames."
        ],
        "beg": [
            "🫦 {user} begged on their knees, whimpering for attention until their spirit broke. Earned **{reward}** Flames.",
            "🫦 {user} groveled at the Master's boots, licking the dirt for **{reward}** Flames.",
            "🫦 {user} licked a guest's stilettos, moaning as they were stepped on. Earned **{reward}** Flames.",
            "🫦 {user} performed a shameful, nude display for the crowd's amusement. Earned **{reward}** Flames.",
            "🫦 {user} wore a 'Useless Asset' sign while begging in the square. Earned **{reward}** Flames.",
            "🫦 {user} spent 2 hours in a humiliating stress position to earn **{reward}** Flames.",
            "🫦 {user} crawled through the velvet lounge, begging for scraps of change. Earned **{reward}** Flames.",
            "🫦 {user} admitted to all their forbidden, dirty sins out loud for **{reward}** Flames.",
            "🫦 {user} stood in the cold rain holding a bowl, naked and shivering. Earned **{reward}** Flames.",
            "🫦 {user} offered their bare skin for fresh 'test marks' in exchange for **{reward}** Flames.",
            "🫦 {user} sang a song of total surrender that moved a Madam to give **{reward}** Flames.",
            "🫦 {user} promised to never speak without permission for a month for **{reward}** Flames.",
            "🫦 {user} knelt in the market with a 'Free to Use' tag. Earned **{reward}** Flames.",
            "🫦 {user} whimpered so pathetically that the Guard felt pity. Earned **{reward}** Flames.",
            "🫦 {user} licked the Master's hand like a well-trained pet for **{reward}** Flames.",
            "🫦 {user} exposed their belly like a submissive animal, begging for a pat. Earned **{reward}** Flames.",
            "🫦 {user} wrote 'Property' across their forehead in permanent ink for **{reward}** Flames.",
            "🫦 {user} kissed the feet of every guard on duty to receive **{reward}** Flames.",
            "🫦 {user} crawled on all fours following a high-rank, begging for a leash. Earned **{reward}** Flames.",
            "🫦 {user} spent the day as a public punching bag for the lower-ranks. Earned **{reward}** Flames.",
            "🫦 {user} performed a 10-minute tantrum of submission for the Master's amusement. Earned **{reward}** Flames.",
            "🫦 {user} begged a high-society lady to use them as a footrest. Earned **{reward}** Flames.",
            "🫦 {user} offered to have their ears pierced as a sign of ownership for **{reward}** Flames.",
            "🫦 {user} wore a heavy metal bit and allowed a guest to 'ride' them. Earned **{reward}** Flames.",
            "🫦 {user} licked the floor of the VIP lounge after a messy party. Earned **{reward}** Flames.",
            "🫦 {user} knelt in front of the Master's pack of hounds, begging for their approval. Earned **{reward}** Flames.",
            "🫦 {user} offered to be a human target for the Master's spit for **{reward}** Flames.",
            "🫦 {user} whimpered while being lead on a short leash through the dining hall. Earned **{reward}** Flames.",
            "🫦 {user} begged to be locked in the 'Small Box' for an hour to earn **{reward}** Flames.",
            "🫦 {user} offered to have their name permanently erased from the records for **{reward}** Flames.",
            "🫦 {user} crawled through the market with a 'Use me as you wish' sign. Earned **{reward}** Flames.",
            "🫦 {user} begged a guest to brand their own initials into {user}’s skin. Earned **{reward}** Flames.",
            "🫦 {user} spent the afternoon as a public target for wet sponges. Earned **{reward}** Flames.",
            "🫦 {user} whimpered while a group of guards laughed at their lack of pride. Earned **{reward}** Flames.",
            "🫦 {user} begged to be used as a human footrest for the Master’s guests. Earned **{reward}** Flames.",
            "🫦 {user} offered to have their mouth permanently gagged for **{reward}** Flames.",
            "🫦 {user} knelt in the rain until their knees bled, begging for entry. Earned **{reward}** Flames.",
            "🫦 {user} offered to be a live mannequin for the Master's new restrictive wear. Earned **{reward}** Flames.",
            "🫦 {user} whimpered while being used as a human coat-rack for the evening. Earned **{reward}** Flames.",
            "🫦 {user} begged the Master to give them a new, humiliating name. Earned **{reward}** Flames.",
            "🫦 {user} offered to have their skin permanently erased from the records for **{reward}** Flames.",
            "🫦 {user} begged the Master to lock them in the kennel for the night. Earned **{reward}** Flames.",
            "🫦 {user} offered to be a human rug in the Master's bedroom for **{reward}** Flames.",
            "🫦 {user} whimpered while being lead by their piercings through the pit. Earned **{reward}** Flames.",
            "🫦 {user} begged to be used as a target for the Master's personal toys. Earned **{reward}** Flames.",
            "🫦 {user} offered to have their safe-word taken away for a week. Earned **{reward}** Flames.",
            "🫦 {user} crawled behind the Master's guests, collecting their discarded ash. Earned **{reward}** Flames.",
            "🫦 {user} begged to be placed in a sensory deprivation tank for **{reward}** Flames.",
            "🫦 {user} offered to have their body painted with the Master's logo. Earned **{reward}** Flames.",
            "🫦 {user} whimpered while being groomed like a prize-winning pet. Earned **{reward}** Flames.",
            "🫦 {user} begged for the privilege of cleaning the Master's private slippers. Earned **{reward}** Flames.",
            "🫦 {user} offered to be a live target for the Master's new violet wand. Earned **{reward}** Flames.",
            "🫦 {user} knelt in the center of the Pit, begging for the next collar. Earned **{reward}** Flames.",
            "🫦 {user} offered to have their safe-word replaced with the Master's name. Earned **{reward}** Flames.",
            "🫦 {user} whimpered while being fitted for a new, restrictive full-body suit. Earned **{reward}** Flames."
        ],
        "cumcleaner": [
            "💦 {user} cleaned the aftermath of the VIP lounge with their tongue. Earned **{reward}** Flames.",
            "💦 {user} spent the shift on all fours, making sure the floor was slick and clean. Earned **{reward}** Flames.",
            "💦 {user} collected the 'leavings' from the heavy play area in a silver cup. Earned **{reward}** Flames.",
            "💦 {user} scrubbed the stains from the velvet cushions while blindfolded. Earned **{reward}** Flames.",
            "💦 {user} used their own mouth to ensure the Master's throne was spotless. Earned **{reward}** Flames.",
            "💦 {user} sanitized the 'Red Cage' after a messy, group session. Earned **{reward}** Flames.",
            "💦 {user} drained the fluid traps in the basement, smelling of spent lust. Earned **{reward}** Flames.",
            "💦 {user} washed the Master's personalized 'toys' with careful attention. Earned **{reward}** Flames.",
            "💦 {user} gathered the discarded latex and disposed of it quietly. Earned **{reward}** Flames.",
            "💦 {user} ensured the scent of the previous session was erased from the air. Earned **{reward}** Flames.",
            "💦 {user} was used as a human mop to dry the tiles of the wet-room. Earned **{reward}** Flames.",
            "💦 {user} carefully filtered the overflow from the Master's private pool. Earned **{reward}** Flames.",
            "💦 {user} sanitized the leather slings until they shone with care. Earned **{reward}** Flames.",
            "💦 {user} cleared the 'remnants' of a legendary climax. Earned **{reward}** Flames.",
            "💦 {user} cleaned the Master's leather gear after a session. Earned **{reward}** Flames.",
            "💦 {user} spent hours scrubbing the marks of a high-intensity session from the stone. Earned **{reward}** Flames.",
            "💦 {user} collected all the used napkins from the voyeur's gallery. Earned **{reward}** Flames.",
            "💦 {user} hand-washed the Master's favorite rubber hood. Earned **{reward}** Flames.",
            "💦 {user} sanitized the medical-grade examination table after 'research'. Earned **{reward}** Flames.",
            "💦 {user} polished the latex floor until it was too slippery to stand on. Earned **{reward}** Flames.",
            "💦 {user} cleared the drains of the shared showers, finding lost hair and rings. Earned **{reward}** Flames.",
            "💦 {user} detailed the intricate carvings on the X-frame with a toothbrush. Earned **{reward}** Flames.",
            "💦 {user} gathered the broken glass from the 'Impact Zone'. Earned **{reward}** Flames.",
            "💦 {user} sanitized the high-voltage electrodes after a group experiment. Earned **{reward}** Flames.",
            "💦 {user} spent the shift drying the sweat from the Master's private gym equipment. Earned **{reward}** Flames.",
            "💦 {user} scrubbed the leather upholstery of the Master's private car. Earned **{reward}** Flames.",
            "💦 {user} hand-washed the Master's collection of silk blindfolds. Earned **{reward}** Flames.",
            "💦 {user} sanitized the Master’s favorite flogger after a heavy session. Earned **{reward}** Flames.",
            "💦 {user} spent the night cleaning the 'Sinner's Pit' after a messy use. Earned **{reward}** Flames.",
            "💦 {user} was used as a human dryer for the Master’s silk towels. Earned **{reward}** Flames.",
            "💦 {user} hand-polished the silver rivets on the Master's private bed-frame. Earned **{reward}** Flames.",
            "💦 {user} sanitized the Master's private medical-grade examination chair. Earned **{reward}** Flames.",
            "💦 {user} spent the shift scrubbing the scent of arousal from the air filters. Earned **{reward}** Flames.",
            "💦 {user} hand-washed the Master's personal collection of velvet masks. Earned **{reward}** Flames.",
            "💦 {user} detailed the chrome bars on the Master's private cage. Earned **{reward}** Flames.",
            "💦 {user} sanitized the floor of the VIP lounge after a high-stakes party. Earned **{reward}** Flames.",
            "💦 {user} scrubbed the Master's collection of custom-made leather collars. Earned **{reward}** Flames.",
            "💦 {user} spent the night detailing the 'Dungeon Master's' personal play-room. Earned **{reward}** Flames.",
            "💦 {user} sanitized the Master's private collection of silver piercings. Earned **{reward}** Flames.",
            "💦 {user} hand-polished the Master's private collection of crystal glassware. Earned **{reward}** Flames.",
            "💦 {user} cleaned the 'Sensory Chamber' after a 12-hour session. Earned **{reward}** Flames.",
            "💦 {user} hand-washed the Master's collection of silk and leather gloves. Earned **{reward}** Flames.",
            "💦 {user} sanitized the Master’s private examination table after a long use. Earned **{reward}** Flames.",
            "💦 {user} spent the night cleaning the 'Wet Room' floor until it reflected their moans. Earned **{reward}** Flames.",
            "💦 {user} was used to test the absorption of new, high-grade dungeon towels. Earned **{reward}** Flames.",
            "💦 {user} hand-polished the Master's private collection of gold-plated gags. Earned **{reward}** Flames.",
            "💦 {user} sanitized the Master's personal collection of glass toys. Earned **{reward}** Flames.",
            "💦 {user} spent the shift scrubbing the sweat from the Master's private training equipment. Earned **{reward}** Flames.",
            "💦 {user} hand-washed the Master's collection of restricted-wear latex. Earned **{reward}** Flames.",
            "💦 {user} detailed the intricate silver chains on the Master's private swing. Earned **{reward}** Flames.",
            "💦 {user} sanitized the floor of the 'Dark Room' after a group session. Earned **{reward}** Flames.",
            "💦 {user} scrubbed the Master's collection of custom-made leather collars. Earned **{reward}** Flames.",
            "💦 {user} spent the night detailing the 'Master’s Throne Room' for a private party. Earned **{reward}** Flames.",
            "💦 {user} sanitized the Master's private collection of vibrating sensors. Earned **{reward}** Flames.",
            "💦 {user} hand-polished the Master's private collection of silver nipple-clamps. Earned **{reward}** Flames."
        ],
        "pimp": [
            "👠 {user} managed a stable of hungry submissives for the night. Earned **{reward}** Flames.",
            "👠 {user} negotiated a high-price contract for a shadow-rank asset. Earned **{reward}** Flames.",
            "👠 {user} broke in a new, crying recruit for the dungeon's service. Earned **{reward}** Flames.",
            "👠 {user} rented out a private booth for an hour of 'education'. Earned **{reward}** Flames.",
            "👠 {user} sold the rights to a public flogging event to the highest bidder. Earned **{reward}** Flames.",
            "👠 {user} coordinated a group 'use' session for the elite members. Earned **{reward}** Flames.",
            "👠 {user} scouted the new arrivals for 'high-sensual potential'. Earned **{reward}** Flames.",
            "👠 {user} ensured every asset was properly marked, branded, and collared. Earned **{reward}** Flames.",
            "👠 {user} traded a week of a sub's service for **{reward}** Flames.",
            "👠 {user} organized an auction for a 'Virgin Asset'. Earned **{reward}** Flames.",
            "👠 {user} leased a specialist submissive to the Master's guest. Earned **{reward}** Flames.",
            "👠 {user} sold a 'Mystery Package' containing a bound submissive. Earned **{reward}** Flames.",
            "👠 {user} hosted a workshop on 'Total Surrender' for a fee. Earned **{reward}** Flames.",
            "👠 {user} upgraded the equipment in the dungeon wing. Earned **{reward}** Flames.",
            "👠 {user} charged a 'protection fee' from the lower-tier assets. Earned **{reward}** Flames.",
            "👠 {user} blackmailed a high-rank using photos from a secret session. Earned **{reward}** Flames.",
            "👠 {user} organized a 'Hunt the Sub' event in the basement forest. Earned **{reward}** Flames.",
            "👠 {user} sold the exclusive rights to a tribute's safe-word for **{reward}** Flames.",
            "👠 {user} managed the distribution of 'The Master's Potion' to the tributes. Earned **{reward}** Flames.",
            "👠 {user} curated a private gallery showing the marks of the week's best assets. Earned **{reward}** Flames.",
            "👠 {user} sold seats to the voyeur's box for the upcoming Final Use. Earned **{reward}** Flames.",
            "👠 {user} brokered a deal for a new shipment of high-grade pheromones. Earned **{reward}** Flames.",
            "👠 {user} organized a 'Submissive Beauty Pageant' for the elite guests. Earned **{reward}** Flames.",
            "👠 {user} sold the exclusive rights to name the Master’s newest pet. Earned **{reward}** Flames.",
            "👠 {user} brokered a contract for a new set of custom-made iron shackles. Earned **{reward}** Flames.",
            "👠 {user} organized a 'Dungeon Master's Masterclass' for the up-and-coming pimps. Earned **{reward}** Flames.",
            "👠 {user} sold the secret location of the Master’s private getaway dungeon. Earned **{reward}** Flames.",
            "👠 {user} brokered a deal for a new line of medical-grade examination chairs. Earned **{reward}** Flames.",
            "👠 {user} organized a 'Private Slave Auction' for the highest-ranking pimps. Earned **{reward}** Flames.",
            "👠 {user} sold the exclusive rights to document the Master’s personal library. Earned **{reward}** Flames.",
            "👠 {user} brokered a deal for a new set of high-voltage sensory equipment. Earned **{reward}** Flames.",
            "👠 {user} organized a 'Dungeon-Wide Talent Show' to scout for new assets. Earned **{reward}** Flames.",
            "👠 {user} sold the exclusive rights to clean the Master’s private office. Earned **{reward}** Flames.",
            "👠 {user} brokered a deal for a new shipment of high-quality leather. Earned **{reward}** Flames.",
            "👠 {user} arranged for a high-rank to take over a tribute’s debt for **{reward}** Flames.",
            "👠 {user} sold the rights to a 'Dungeon Documentary' featuring the pit. Earned **{reward}** Flames.",
            "👠 {user} brokered a deal for a new shipment of premium, scented latex. Earned **{reward}** Flames.",
            "👠 {user} organized a 'Gag-Only' banquet for the Master's elite inner circle. Earned **{reward}** Flames.",
            "👠 {user} sold the exclusive rights to witness a 'Total Surrender' ceremony. Earned **{reward}** Flames.",
            "👠 {user} brokered a contract for a new shipment of medical-grade blindfolds. Earned **{reward}** Flames.",
            "👠 {user} organized a 'Hunt the High-Rank' game for the tributes. Earned **{reward}** Flames.",
            "👠 {user} sold the secret code to the Master’s private toy-vault. Earned **{reward}** Flames.",
            "👠 {user} brokered a deal for a new line of titanium nipple-clamps. Earned **{reward}** Flames.",
            "👠 {user} organized a 'Fetish Fashion Show' to display the newest assets. Earned **{reward}** Flames.",
            "👠 {user} sold the exclusive rights to name the Master’s newest dungeon-hound. Earned **{reward}** Flames.",
            "👠 {user} brokered a deal for a new shipment of high-tensile strength silk ropes. Earned **{reward}** Flames.",
            "👠 {user} organized a 'Dungeon-Wide Scavenger Hunt' for the elite pimps. Earned **{reward}** Flames.",
            "👠 {user} sold the exclusive rights to clean the Master’s personal bed-chamber. Earned **{reward}** Flames.",
            "👠 {user} brokered a deal for a new shipment of premium, hand-crafted leather whips. Earned **{reward}** Flames."
        ],
        "experiment": [
            "🧪 {user} volunteered for a mind-melting sensory-deprivation test. Earned **{reward}** Flames.",
            "🧪 {user} was strapped into the 'Tesla-Chair' for an endurance test. Earned **{reward}** Flames.",
            "🧪 {user} ingested an experimental pheromone and lost all bodily control. Earned **{reward}** Flames.",
            "🧪 {user} spent the night in a vibration-pod, vibrating to the bone. Earned **{reward}** Flames.",
            "🧪 {user} was subjected to a cold-water, naked conditioning trial. Earned **{reward}** Flames.",
            "🧪 {user} tested a prototype 'Mind-Control' collar that forced moaning. Earned **{reward}** Flames.",
            "🧪 {user} was used to calibrate the pain-pleasure threshold device. Earned **{reward}** Flames.",
            "🧪 {user} lived as a literal laboratory animal for 3 hours. Earned **{reward}** Flames.",
            "🧪 {user} underwent 'Red-Light' psychological re-coding. Earned **{reward}** Flames.",
            "🧪 {user} had their safe word temporarily revoked for research. Earned **{reward}** Flames.",
            "🧪 {user} allowed their senses to be linked to a computer for data. Earned **{reward}** Flames.",
            "🧪 {user} spent the shift in a vacuum-sealed chamber with limited oxygen. Earned **{reward}** Flames.",
            "🧪 {user} was injected with a substance that turned their skin blue. Earned **{reward}** Flames.",
            "🧪 {user} allowed a doctor to map their pleasure-nerves with tiny needles. Earned **{reward}** Flames.",
            "🧪 {user} spent hours in a magnetic field that made them hallucinate. Earned **{reward}** Flames.",
            "🧪 {user} was used to test the range of a new remote-control vibrator. Earned **{reward}** Flames.",
            "🧪 {user} allowed their dreams to be recorded and projected for the crowd. Earned **{reward}** Flames.",
            "🧪 {user} spent the night in a 'Lust Tank' filled with thick jelly. Earned **{reward}** Flames.",
            "🧪 {user} was used to test the durability of a new carbon-fiber flogger. Earned **{reward}** Flames.",
            "🧪 {user} allowed their vocal cords to be numbed to see if they could still moan. Earned **{reward}** Flames.",
            "🧪 {user} spent the shift wearing a 'Weight Loss' suit made of heavy rubber. Earned **{reward}** Flames.",
            "🧪 {user} allowed their safe-word to be replaced with a complex math problem. Earned **{reward}** Flames.",
            "🧪 {user} spent hours in a room where the floor was a giant speaker. Earned **{reward}** Flames.",
            "🧪 {user} allowed a student to practice 'Anatomical Marking' on their skin. Earned **{reward}** Flames.",
            "🧪 {user} spent the night in a suit that simulated the touch of a hundred hands. Earned **{reward}** Flames.",
            "🧪 {user} allowed their pupils to be permanently dilated to see how it affected their submission. Earned **{reward}** Flames.",
            "🧪 {user} spent the shift in a chamber that simulated the pressure of 2 miles underwater. Earned **{reward}** Flames.",
            "🧪 {user} was used to test a new line of medical-grade gags that monitor heart rate. Earned **{reward}** Flames.",
            "🧪 {user} allowed their nerves to be temporarily 'rewired' to feel the Master's touch 100x stronger. Earned **{reward}** Flames.",
            "🧪 {user} spent the night in a 'Sensory Overflow' box that played the Master's voice on repeat. Earned **{reward}** Flames.",
            "🧪 {user} allowed their skin to be temporarily coated in a silver, conductive paint. Earned **{reward}** Flames.",
            "🧪 {user} was used to test the effects of long-term isolation in a mirrored room. Earned **{reward}** Flames.",
            "🧪 {user} allowed their motor skills to be controlled via a remote device for 4 hours. Earned **{reward}** Flames.",
            "🧪 {user} spent the shift in a chamber that simulated the heat of a desert and the cold of the arctic. Earned **{reward}** Flames.",
            "🧪 {user} allowed their memory of the last hour to be temporarily erased for research. Earned **{reward}** Flames.",
            "🧪 {user} was used to test a new line of high-tensile strength silk ropes. Earned **{reward}** Flames.",
            "🧪 {user} allowed their brain-waves to be converted into a song for the audience. Earned **{reward}** Flames.",
            "🧪 {user} spent the night in a tank filled with a substance that simulates the weight of 50 hands. Earned **{reward}** Flames.",
            "🧪 {user} allowed their eyes to be temporarily altered to see in the dark for a session. Earned **{reward}** Flames.",
            "🧪 {user} was used to test a new line of ultrasonic whips that strike without sound. Earned **{reward}** Flames.",
            "🧪 {user} allowed their body temperature to be lowered to see if they could still feel the Master's heat. Earned **{reward}** Flames.",
            "🧪 {user} spent the shift in a room where every surface was covered in soft velvet. Earned **{reward}** Flames.",
            "🧪 {user} was used to test the effects of 24-hour constant, low-level vibration. Earned **{reward}** Flames.",
            "🧪 {user} allowed their reflexes to be temporarily 'shut down' to see if they could still kneel. Earned **{reward}** Flames.",
            "🧪 {user} spent the night in a 'Total Bliss' tank that simulations the perfect use. Earned **{reward}** Flames.",
            "🧪 {user} allowed their skin to be temporarily 'tattooed' with a glowing substance. Earned **{reward}** Flames.",
            "🧪 {user} was used to test the range of a new line of psychic-link sensors. Earned **{reward}** Flames.",
            "🧪 {user} allowed their senses to be linked to a music-box for the crowd. Earned **{reward}** Flames.",
            "🧪 {user} spent the shift in a room where the air was 50% oxygen and 50% musk. Earned **{reward}** Flames.",
            "🧪 {user} allowed their body-fat percentage to be monitored during a 6-hour use. Earned **{reward}** Flames.",
            "🧪 {user} was used to test a new line of high-quality, medical-grade blindfolds. Earned **{reward}** Flames.",
            "🧪 {user} allowed their heart-rate to be converted into a rhythmic drum-beat for the lounge. Earned **{reward}** Flames.",
            "🧪 {user} spent the night in a chamber that simulated the weight of a heavy iron shackle. Earned **{reward}** Flames.",
            "🧪 {user} allowed their safe-word to be replaced with a 10-digit number. Earned **{reward}** Flames.",
            "🧪 {user} was used to test the endurance of a new line of carbon-fiber cages. Earned **{reward}** Flames.",
            "🧪 {user} allowed their breathing to be synchronized with a machine for 4 hours. Earned **{reward}** Flames.",
            "🧪 {user} spent the shift in a chamber that simulated the scent of the Master’s private study. Earned **{reward}** Flames.",
            "🧪 {user} allowed their skin’s sensitivity to be temporarily increased by 500%. Earned **{reward}** Flames.",
            "🧪 {user} was used to test the effects of a new line of high-grade, scented massage oils. Earned **{reward}** Flames.",
            "🧪 {user} allowed their motor skills to be controlled via a high-frequency sensor. Earned **{reward}** Flames."
        ],
        "mystery": [
            "❓ {user} walked into a dark room blindfolded and came out changed. Earned **{reward}** Flames.",
            "❓ {user} followed a hooded figure into the deep basement for a session. Earned **{reward}** Flames.",
            "❓ {user} found a secret hatch in the padded cell. Earned **{reward}** Flames.",
            "❓ {user} woke up in the Master's bed with no memory and new marks. Earned **{reward}** Flames.",
            "❓ {user} was given a mysterious 'White Pill' by the dungeon nurse. Earned **{reward}** Flames.",
            "❓ {user} discovered an unlocked door leading to the 'Private Wing'. Earned **{reward}** Flames.",
            "❓ {user} was forced to choose between two unmarked keys. Earned **{reward}** Flames.",
            "❓ {user} accepted a dare from the dungeon's oldest inhabitant. Earned **{reward}** Flames.",
            "❓ {user} spent an hour listening to the moans behind the steel door. Earned **{reward}** Flames.",
            "❓ {user} found a discarded, stained pouch near the flogging post. Earned **{reward}** Flames.",
            "❓ {user} was forced to participate in a blind-folded taste test of 'Liquids'. Earned **{reward}** Flames.",
            "❓ {user} found a map leading to the Master's secret, private dungeon. Earned **{reward}** Flames.",
            "❓ {user} was asked to deliver a locked box that was clearly vibrating. Earned **{reward}** Flames.",
            "❓ {user} found a letter from a past tribute addressed to 'The One Who Follows'. Earned **{reward}** Flames.",
            "❓ {user} was forced to play a game of 'Russian Roulette' with a cattle prod. Earned **{reward}** Flames.",
            "❓ {user} found a hidden camera in the shared showers and kept the footage. Earned **{reward}** Flames.",
            "❓ {user} was asked to model a new set of gear for an unknown client. Earned **{reward}** Flames.",
            "❓ {user} found a vial of the Master's personal scent and used it. Earned **{reward}** Flames.",
            "❓ {user} was forced to stand still while a stranger mapped their body. Earned **{reward}** Flames.",
            "❓ {user} found a secret compartment in their own collar. Earned **{reward}** Flames.",
            "❓ {user} was asked to judge a 'Best Mark' competition between other tributes. Earned **{reward}** Flames.",
            "❓ {user} found a high-rank's lost mask and returned it for a reward. Earned **{reward}** Flames.",
            "❓ {user} was asked to whisper their darkest secret into a stone wall. Earned **{reward}** Flames.",
            "❓ {user} found a stash of contraband sweets hidden in the toy vault. Earned **{reward}** Flames.",
            "❓ {user} was asked to hold a candle for a session they weren't allowed to see. Earned **{reward}** Flames.",
            "❓ {user} was asked to sign an unmarked contract while blindfolded. Earned **{reward}** Flames.",
            "❓ {user} found a key that opens a door in the Master's private garden. Earned **{reward}** Flames.",
            "❓ {user} was asked to count the number of stripes on a high-rank's back. Earned **{reward}** Flames.",
            "❓ {user} found a lost pendant that contains a photo of a past Master. Earned **{reward}** Flames.",
            "❓ {user} was asked to lead a stranger through the dungeon’s maze. Earned **{reward}** Flames.",
            "❓ {user} found a small box that contains a lock of the Master’s hair. Earned **{reward}** Flames.",
            "❓ {user} was asked to choose between a week of silence or a night in the pit. Earned **{reward}** Flames.",
            "❓ {user} found a diary that describes the Red Room's origins. Earned **{reward}** Flames.",
            "❓ {user} was asked to stand in a circle of salt for 2 hours. Earned **{reward}** Flames.",
            "❓ {user} found a lost wedding ring in the 'Impact Zone'. Earned **{reward}** Flames.",
            "❓ {user} was asked to paint a portrait of the Master from memory. Earned **{reward}** Flames.",
            "❓ {user} found a secret passage behind a velvet curtain. Earned **{reward}** Flames.",
            "❓ {user} was asked to drink a liquid that tastes like metal and honey. Earned **{reward}** Flames.",
            "❓ {user} found a lost earring that belongs to the Winner of the 10th Edition. Earned **{reward}** Flames.",
            "❓ {user} was asked to whisper the name of the person they hate the most into a hole. Earned **{reward}** Flames.",
            "❓ {user} found a small glass eye hidden in the laundry room. Earned **{reward}** Flames.",
            "❓ {user} was asked to perform a 10-minute 'Private Show' for a hooded figure. Earned **{reward}** Flames.",
            "❓ {user} found a small bag of white powder that smells of vanilla. Earned **{reward}** Flames.",
            "❓ {user} was asked to lead a blindfolded stranger to the Master's office. Earned **{reward}** Flames.",
            "❓ {user} found a secret key hidden in a piece of fruit. Earned **{reward}** Flames.",
            "❓ {user} was asked to write a letter of apology to an unknown person. Earned **{reward}** Flames.",
            "❓ {user} found a lost collar that still has the Master's scent on it. Earned **{reward}** Flames.",
            "❓ {user} was asked to spend an hour in a room filled with mirrors. Earned **{reward}** Flames.",
            "❓ {user} found a hidden trapdoor in the Master's bedroom. Earned **{reward}** Flames.",
            "❓ {user} was asked to taste-test a new line of premium, flavored lubricants. Earned **{reward}** Flames.",
            "❓ {user} found a lost earring that belongs to the Master’s favorite asset. Earned **{reward}** Flames.",
            "❓ {user} was asked to whisper their deepest desire into a high-rank’s ear. Earned **{reward}** Flames.",
            "❓ {user} found a secret room filled with the Master's old diaries. Earned **{reward}** Flames.",
            "❓ {user} was asked to hold a candle for a session involving the Master's elite. Earned **{reward}** Flames.",
            "❓ {user} found a lost locket containing a lock of hair and a safe-word. Earned **{reward}** Flames.",
            "❓ {user} was asked to choose between a night of service or a week of silence. Earned **{reward}** Flames.",
            "❓ {user} found a secret passage leading to the dungeon’s rooftop. Earned **{reward}** Flames.",
            "❓ {user} was asked to sign a contract that grants their soul to the Winner. Earned **{reward}** Flames.",
            "❓ {user} found a small box containing a single, gold-plated needle. Earned **{reward}** Flames.",
            "❓ {user} was asked to lead a group of blindfolded tributes to the Pit. Earned **{reward}** Flames.",
            "❓ {user} found a secret passage behind a mirror in the VIP lounge. Earned **{reward}** Flames."
        ],
        "flirt": [
            "🫦 {user} charmed a wealthy donor in the Velvet Lounge. They left **{reward}** Flames.",
            "🫦 {user} used their 'assets' to distract the treasury guard. Swiped **{reward}** Flames.",
            "🫦 {user} seduced a high-ranking officer for their pouch. Earned **{reward}** Flames.",
            "🫦 {user} teased the audience until they threw money at the stage. Earned **{reward}** Flames.",
            "🫦 {user} whispered forbidden desires into a patron's ear. Earned **{reward}** Flames.",
            "🫦 {user} danced naked in the 'Sinner's Cage' for 30 minutes. Earned **{reward}** Flames.",
            "🫦 {user} promised a night of service to the highest bidder. Earned **{reward}** Flames.",
            "🫦 {user} displayed their fresh marks to an appreciative crowd. Earned **{reward}** Flames.",
            "🫦 {user} let a stranger choose their next 'punishment' for **{reward}** Flames.",
            "🫦 {user} served drinks while wearing only a collar and apron. Earned **{reward}** Flames.",
            "🫦 {user} performed a 5-minute lap dance for a high-rank officer. Earned **{reward}** Flames.",
            "🫦 {user} used their mouth to feed a donor, earning a tip. Earned **{reward}** Flames.",
            "🫦 {user} posed for the dungeon's professional photographer. Earned **{reward}** Flames.",
            "🫦 {user} allowed a guest to draw 'Art' on their skin with markers. Earned **{reward}** Flames.",
            "🫦 {user} spent the night in the 'VIP Window' for the street-viewers. Earned **{reward}** Flames.",
            "🫦 {user} whispered the Master's name with such lust it moved a guard to give **{reward}** Flames.",
            "🫦 {user} allowed a stranger to brush their hair for an hour. Earned **{reward}** Flames.",
            "🫦 {user} performed a strip-tease that resulted in a standing ovation. Earned **{reward}** Flames.",
            "🫦 {user} used their eyes to hypnotize a rookie guard into giving **{reward}** Flames.",
            "🫦 {user} allowed a guest to 'Test the Goods' with a single touch. Earned **{reward}** Flames.",
            "🫦 {user} spent the afternoon as a live model in a fetish-clothing store. Earned **{reward}** Flames.",
            "🫦 {user} promised to dream only of the person who gave them the most Flames. Earned **{reward}** Flames.",
            "🫦 {user} performed a private show in the 'Velvet Mirror Room'. Earned **{reward}** Flames.",
            "🫦 {user} used their tongue to write their name on a guest's palm. Earned **{reward}** Flames.",
            "🫦 {user} allowed a high-rank to choose their perfume for the week. Earned **{reward}** Flames.",
            "🫦 {user} performed a 'Siren’s Dance' while bound in sheer silk. Earned **{reward}** Flames.",
            "🫦 {user} teased a donor by blowing them a kiss through a metal gag. Earned **{reward}** Flames.",
            "🫦 {user} spent the hour as a human 'Art Installation' in the center of the lounge. Earned **{reward}** Flames.",
            "🫦 {user} allowed a guest to feed them chocolate while blindfolded. Earned **{reward}** Flames.",
            "🫦 {user} whispered their own measurements into a high-rank’s ear for **{reward}** Flames.",
            "🫦 {user} performed a 2-minute 'Touch-Me-Not' tease for the elite box. Earned **{reward}** Flames.",
            "🫦 {user} allowed a stranger to count every mark on their back with their fingers. Earned **{reward}** Flames.",
            "🫦 {user} spent the shift wearing the Master’s favorite scent and nothing else. Earned **{reward}** Flames.",
            "🫦 {user} performed a private show for a guest while restricted by a straitjacket. Earned **{reward}** Flames.",
            "🫦 {user} whispered a high-rank’s deepest secrets back to them for **{reward}** Flames.",
            "🫦 {user} allowed a donor to pick their next outfit for the lounge. Earned **{reward}** Flames.",
            "🫦 {user} performed a 'Siren’s Dance' while bound in sheer silk. Earned **{reward}** Flames.",
            "🫦 {user} teased a group of guards by slowly polishing their own collar. Earned **{reward}** Flames.",
            "🫦 {user} allowed a guest to choose their next 'Service' for the night. Earned **{reward}** Flames.",
            "🫦 {user} whispered their own 'Market Price' to a potential buyer for **{reward}** Flames.",
            "🫦 {user} performed a 10-minute 'Naked Yoga' show for the voyeur's gallery. Earned **{reward}** Flames.",
            "🫦 {user} used their mouth to feed the Master’s personal guard, earning a tip. Earned **{reward}** Flames.",
            "🫦 {user} posed for the Master’s private photography collection. Earned **{reward}** Flames.",
            "🫦 {user} allowed a guest to write their name on {user}’s skin with their tongue. Earned **{reward}** Flames.",
            "🫦 {user} spent the night as a human display in the Master's private foyer. Earned **{reward}** Flames.",
            "🫦 {user} whispered the names of every past winner with such lust it moved the Master. Earned **{reward}** Flames.",
            "🫦 {user} allowed a stranger to brush their bare skin for an hour. Earned **{reward}** Flames.",
            "🫦 {user} performed a private show for the Master’s elite inner circle. Earned **{reward}** Flames.",
            "🫦 {user} used their eyes to hypnotize the Master himself into giving **{reward}** Flames.",
            "🫦 {user} allowed a high-rank to choose their safe-word for the session. Earned **{reward}** Flames.",
            "🫦 {user} spent the afternoon as a live model for the dungeon’s new line of restricted-wear. Earned **{reward}** Flames.",
            "🫦 {user} promised to be the Master’s personal pet for the next 24 hours for **{reward}** Flames.",
            "🫦 {user} performed a private show in the Master's 'Velvet Mirror Room'. Earned **{reward}** Flames.",
            "🫦 {user} used their mouth to write a high-rank’s name on their own thigh. Earned **{reward}** Flames.",
            "🫦 {user} allowed the Master to choose their next 'Use' for the night. Earned **{reward}** Flames."
        ]
    }

    @classmethod
    def get_intro(cls): 
        if not cls.INTRO_MESSAGES: return "🔞 **The Red Room opens.**"
        return random.choice(cls.INTRO_MESSAGES)

    @classmethod
    def get_kill(cls, winner, loser, is_final=False):
        try:
            if is_final: 
                if not cls.FINAL_KILL_MESSAGES: return f"👑 **Winner:** {winner}"
                return random.choice(cls.FINAL_KILL_MESSAGES).format(winner=winner, loser=loser)
            
            if not (cls.OPENERS and cls.ACTIONS and cls.FINISHERS):
                return f"⚔️ {winner} dominated {loser}."
                
            o = random.choice(cls.OPENERS).format(winner=winner, loser=loser)
            a = random.choice(cls.ACTIONS).format(winner=winner, loser=loser)
            f = random.choice(cls.FINISHERS).format(winner=winner, loser=loser)
            return f"🔥 {o} {a} {f}"
        except Exception as e: 
            print(f"Lexicon Kill Error: {e}")
            return f"⚔️ {winner} dominated {loser}."

    @classmethod
    def get_legendary_event(cls, losers_names):
        try: 
            if not cls.LEGENDARY_EVENTS: return "⚠️ A chaotic event cleared several tributes."
            return random.choice(cls.LEGENDARY_EVENTS).format(losers=", ".join(str(l) for l in losers_names))
        except Exception as e: 
            print(f"Lexicon Event Error: {e}")
            return "⚠️ A chaotic event cleared several tributes."

    @classmethod
    def get_economy_msg(cls, cmd, user, reward):
        try: 
            if cmd not in cls.ECONOMY_MESSAGES or not cls.ECONOMY_MESSAGES[cmd]:
                return f"💰 {user} earned **{reward}** Flames through effort."
            return random.choice(cls.ECONOMY_MESSAGES[cmd]).format(user=user, reward=reward)
        except Exception as e: 
            print(f"Lexicon Economy Error: {e}")
            return f"💰 {user} earned **{reward}** Flames through effort."

    @classmethod
    def get_winner_announcement(cls, mention):
        try: 
            if not cls.WINNER_PINGS: return f"🏆 {mention} has won!"
            return random.choice(cls.WINNER_PINGS).format(mention=mention)
        except Exception as e: 
            print(f"Lexicon Win Error: {e}")
            return f"🏆 {mention} has won the Fiery Hangrygames Edition!"

    @classmethod
    def get_tension_msg(cls, u1_name, u2_name, count, pct):
        """Added helper for Gallery tension flavor."""
        return f"• {u1_name} 🔗 {u2_name}: {count} exchanges. **[{pct}% TENSION]**"
