import random
import logging
from typing import List, Optional

# Configuração de Logger para sincronização e rastreio de geração de texto
logger = logging.getLogger("SyndicateLexicon")

class PartnersInCrimeLexicon:
    def __init__(self) -> None:
        # 1. Sentenças Gerais de Combate (Retornam exatamente 1 única frase combinando a ação completa)
        self.actions: List[str] = [
            "shoves {loser} roughly onto the soft leather mattress, securing their wrists high above their head while they plead for mercy",
            "blindsides {loser} near the St. Andrew's cross, snapping a heavy padded leather collar shut around their neck with an ominous click",
            "corners {loser} against the mirrored wall of the dungeon, stripping away their lace harness to expose their shivering skin",
            "glares down {loser} beneath the dim red lights, forcing them onto their knees in complete, trembling submission",
            "pins {loser} face-first against the cold steel suspension frame, completely trapping them with swift rope wraps",
            "catches {loser} off-guard, sliding a smooth silicone ball gag between their lips to muffle their breathless gasps",
            "unleashes a stinging volley of leather crop strikes straight to {loser}'s thighs, breaking their stubborn willpower",
            "disarms {loser}'s resistance completely with a tight, inescapable velvet harness that forces their chin upward",
            "lures {loser} onto the heavy suspension platform, locking their ankle cuffs to the floor rings to take away all control",
            "slams a heavy leather paddle onto {loser}'s bare skin, leaving them writhing in helpless pleasure on the rug",
            "unbuckles {loser}'s leather corset, leaving their chest completely bare and exposed to the cool air of the chamber",
            "traces a cold metal flogger slowly along {loser}'s ribs, sending intense shivers of anticipation down their spine",
            "forces {loser} down onto the custom velvet kneeling cushion, securing their hands behind their back with silk ties",
            "tears away {loser}'s delicate lace top, leaving them completely bare and flushing red under the red chandelier",
            "runs a cold ice cube slowly down {loser}'s spine, forcing a broken, high-pitched whimper from their lips",
            "traps {loser} inside the padded sensory cage, locking their wrists behind them with absolute playroom authority",
            "squeezes a pair of soft velvet-lined clamps onto {loser}'s sensitive areas, completely shattering their sensory defenses",
            "locks {loser}'s fingers in heavy leather mitts, leaving them totally defenseless and at the mercy of their Master",
            "applies a drop of warm, skin-safe lavender wax directly onto {loser}'s bare shoulder, making them gasp dramatically",
            "pulls {loser}'s collar leash with sudden force, dragging them flat onto the leather spanking bench in submission",
            "slides a thick leather blindfold over {loser}'s eyes, plunging their world into complete, helpless sensory darkness",
            "runs a cold metal wheel over {loser}'s warm, exposed stomach, raising goosebumps along their sensitive skin",
            "tightens the ropes around {loser}'s thighs, forcing them to hold a vulnerable, submissive kneeling posture",
            "rips off {loser}'s satin undershirt, leaving them standing naked and trembling under the glaring spotlight",
            "shackles {loser}'s wrists to the heavy wooden pillory, completely neutralizing any remaining hope of escape",
            "subdues {loser} beneath the soft glow of the hanging chandelier, forcing them to surrender their pride on all fours",
            "unleashes a rhythmic spanking with a wide wooden ruler across {loser}'s rear, leaving a warm red glow behind",
            "pins {loser} to the padded examination table, securing their ankles to the steel stirrups in complete exposure",
            "runs a soft fur whip slowly along {loser}'s spine, sending intense shivers through their body to their hips",
            "tightens the leather handcuffs around {loser}'s wrists, completely restricting their movement to absolute zero",
            "strips away {loser}'s silk underwear with a decisive pull, exposing their bound posture in the playroom mirror",
            "drags {loser} onto the elevated leather chaise, securing their ankles to the brass posts with heavy velvet ropes",
            "clips {loser}'s wrist restraints to the overhead suspension bar, watching their balance slip away instantly",
            "presses a vibrating sensory toy flat against {loser}'s warm neck, breaking their focus with immediate heat",
            "spins {loser} around to lock their wrists behind them, ensuring absolute confinement with double-locked steel cuffs",
            "forces a soft silicone ring gag over {loser}'s lips, completely containing their protests to muffled whimpers",
            "slides a cold, heavy metal chain through {loser}'s belt loops, dragging them to the foot of the throne",
            "traces the tip of a carbon fiber crop over {loser}'s bare chest, sending sharp ripples of anticipation through them",
            "shoves {loser} against the wooden cross beams, fastening the leather waist strap with a definitive click",
            "unlaces {loser}'s heavy boots, leaving them completely barefoot and vulnerable on the cold concrete floor",
            "applies a cold satin blindfold to {loser}'s face, whispering playroom instructions directly into their ear",
            "unleashes a flurry of soft leather paddle taps across {loser}'s shoulders, warming their skin to a deep crimson flush",
            "locks {loser}'s neck inside a stiff leather posture collar, forcing them to hold their head high in complete submission",
            "stretches {loser}'s arms wide with a padded spreader bar, eliminating any remaining slack for resistance",
            "tears away {loser}'s velvet shirt sleeves, exposing their bare arms to the cool drafts of the private cellar",
            "traces a heavy metal padlock key slowly down {loser}'s bare stomach, teasing their limits with cold pressure",
            "anchors {loser}'s collar chain directly to the low floor ring, keeping them completely locked in a kneeling position",
            "snaps heavy velcro restraints around {loser}'s ankles, parting their legs wide on the plush sheepskin rug",
            "unbuckles {loser}'s decorative harness, letting the leather straps fall uselessly to the playroom floor",
            "drips warm chamomile wax onto {loser}'s inner thighs, eliciting a sudden gasp of mixed pleasure and surrender",
            "secures {loser} face-down on the spanking horse, fastening the under-belly straps to prevent any possibility of rolling",
            "locks {loser}'s hands inside a soft padded leather muff, leaving them completely unable to touch anything",
            "swipes low with a heavy feather duster, slicing through {loser}'s remaining sensory defenses with rhythmic strokes",
            "hooks {loser}'s wrists to the suspension pulley, raising them slowly until their toes barely touch the ground",
            "strips away {loser}'s satin robe, leaving them standing entirely bare, shivering, and exposed in the red light",
            "secures {loser} flat against the heavy timber pillar, locking their cuffs behind the solid wood structure",
            "runs a smooth massage stone slowly down {loser}'s bare back, calming their muscles before the next sharp strike",
            "fastens a neoprene hood over {loser}'s head, sealing their sight and voice in complete playroom isolation",
            "shoves {loser} onto the master's footstool, placing a commanding hand on their shoulder to lock them in place",
            "unlaces {loser}'s tight corset strings, exposing their chest and ribs to the dim spotlight of the dungeon",
            "tears off {loser}'s velvet gloves, leaving their bare hands trembling and defenseless under the red chandelier",
            "clicks heavy padlock shackles around {loser}'s neck, establishing absolute playroom ownership in one movement",
            "traces a sharp fingernail slowly across {loser}'s warm collarbone, leaving light pink marks behind",
            "locks {loser} inside the iron wall chains, forcing them to stand fully exposed to the master's gaze",
            "swipes a wet sponge filled with cold water across {loser}'s bare chest, making them shiver in sudden shock",
            "secures {loser}'s wrists to the brass brackets on the wall, stretching their body in beautiful surrender",
            "strips away {loser}'s delicate lace stockings, leaving their bare legs completely cold and vulnerable",
            "presses a warm candle-wax bottle flat against {loser}'s stomach, preparation for the heat to come",
            "locks {loser}'s ankles in the wooden pillory frame, sealing the heavy latch shut with a polished key",
            "unleashes a stinging slap with a wide suede paddle straight to {loser}'s flushed cheeks",
            "forces {loser} flat on the massage table, securing their waist with a wide leather strap to keep them still",
            "traces a soft fur glove slowly along {loser}'s collarbone, heightening their sensory anticipation",
            "secures {loser}'s hips to the wooden spanking bench, locking their hands to the floor rings below",
            "applies a pair of adjustable magnetic clamps to {loser}'s bare chest, raising the physical focus",
            "rips away {loser}'s final silk barrier, leaving them completely bare and surrendered on the velvet cushions",
            "runs a cold metal roller slowly along {loser}'s inner thighs, raising immediate goosebumps on their skin",
            "locks a heavy leather posture collar around {loser}'s neck, forcing their chin up toward the ceiling",
            "secures {loser}'s ankles with matching velcro cuffs, linking them to their collar chain to restrict all posture",
            "tears off {loser}'s satin blindfold, forcing them to witness their bound posture in the heavy vanity mirror",
            "drips a single drop of warm organic oil onto {loser}'s neck, preparing their skin for the touch of the crop",
            "locks {loser}'s wrists to the heavy suspension rings, letting them hang slightly off the leather bolster",
            "strips away {loser}'s velvet waistband, leaving their midriff completely bare and breathing heavily",
            "forces {loser} to kneel on the soft sheepskin rug, securing their wrists to their leather ankle straps",
            "unbuckles {loser}'s shoulder harness, letting all their heavy playroom gear drop to the concrete floor",
            "locks {loser} in the private suspension frame, lifting them slowly off the ground into subspace",
            "runs a warm glass rod slowly down {loser}'s bare stomach, keeping their senses on edge under the red light",
            "secures {loser}'s arms to the high-backed master's chair, locking the heavy wrist straps with precision",
            "tears open {loser}'s buttoned velvet shirt, exposing their warm chest to the cool drafts of the room",
            "locks {loser}'s ankles to the floor rings, forcing them to hold a wide, submissive stance on the rug",
            "presses a cold metal coin slowly against {loser}'s warm, sensitive neck, making them gasp",
            "secures {loser}'s chest with a tight rope harness, making every single breath highly visible",
            "strips away {loser}'s delicate lace trim, exposing their bare skin to the playroom spotlights",
            "locks {loser}'s wrists to the high wooden cross beam, leaving them completely exposed and breathless",
            "runs a soft feather brush slowly along {loser}'s collarbone, teasing their sensory nerves before the strike",
            "forces {loser} onto the submissive bench, hooking their cuffs to the built-in D-rings with a snap",
            "tears away {loser}'s satin slip, exposing their bare chest and stomach under the hanging chandelier",
            "locks {loser}'s hands inside soft velvet mitts, securing them to the base of the master's throne",
            "drips warm lavender wax directly onto {loser}'s bare lower back, eliciting a breathless whimper",
            "secures {loser}'s waist to the spanking horse, fastening the leather straps with absolute precision",
            "shackles {loser}'s hands to the brass wall brackets, leaving them completely bound under the red light",
            "runs a cold steel wand slowly along {loser}'s spine, raising intense shivers down to their hips",
            "locks {loser} in the heavy iron wall chains, demanding their complete and absolute submission right now",
            "strips away {loser}'s lace-trimmed shorts, leaving their bare legs completely exposed to the room",
            "unleashes a final, resounding spank with a wide leather paddle straight to {loser}'s flushed rear",
            "secures {loser}'s wrists with heavy cotton ropes, locking them to the corners of the soft mattress",
            "tears open {loser}'s buttoned corset, leaving their bare waist and ribs exposed to the cold air",
            "locks {loser}'s ankles to the heavy steel spreader bar, restricting their leg movement to absolute zero",
            "runs a smooth ice cube slowly down {loser}'s bare chest, leaving a trail of freezing water on their skin",
            "secures {loser} face-down on the spanking horse, fastening the straps tight to ensure absolute immobility",
            "strips away {loser}'s final lace barrier, leaving them completely bare and vulnerable under the chandelier",
            "locks a posture collar around {loser}'s neck, claiming absolute playroom ownership over their body",
            "drips warm violet wax directly onto {loser}'s bare shoulder, forcing a soft whimper of surrender",
            "secures {loser}'s hands behind their back in one fluid movement, snapping the handcuffs closed",
            "tears off {loser}'s leather collar leash, pulling them closer to the base of the master's chair",
            "locks {loser}'s wrists to the heavy steel cross, ending all possibility of escape for the night",
            "runs a sharp fingernail slowly down {loser}'s bare back, leaving light pink marks along their spine",
            "secures {loser}'s waist strap to the spanking bench, locking their hands in matching wrist cuffs",
            "strips away {loser}'s silk thigh-highs, leaving their bare legs completely vulnerable on the mattress",
            "locks {loser} inside the playroom cage, leaving them completely exposed to any passing dungeon guest",
            "unleashes a stinging strike with a carbon fiber crop right across {loser}'s bare rear",
            "secures {loser}'s wrists to the high suspension pulley, raising their arms to stretch their chest",
            "tears away {loser}'s delicate lace top, leaving their chest entirely bare and breathing rapidly",
            "locks {loser}'s ankles to the wooden pillory, leaving them completely bare and surrendered to the room",
            "runs a cold metal wheel over {loser}'s bare thighs, raising goosebumps along their sensitive skin",
            "secures {loser} flat on the spanking horse, fastening the heavy under-belly straps with a sharp snap",
            "strips away {loser}'s velvet gloves, leaving their bare hands trembling and defenseless on the rug",
            "locks a posture collar around {loser}'s throat, forcing their head back in complete and beautiful exposure",
            "drips warm lavender wax directly onto {loser}'s collarbone, making them gasp under the red lights",
            "secures {loser}'s hands to the wall brackets, keeping them completely locked in a vulnerable posture",
            "tears open {loser}'s buttoned velvet shirt, exposing their warm chest to the cool playroom air",
            "locks {loser} inside the heavy iron cage, sliding the padlock into place with a definitive click",
            "runs a soft fur whip slowly along {loser}'s ribs, sending intense shivers through their body",
            "secures {loser}'s ankles with padded leather cuffs, linking them to the corner rings of the mattress",
            "strips away {loser}'s silk underwear with a single pull, leaving them completely naked on the rug",
            "locks {loser}'s hands behind their back with silk ties, securing them to the base of the cross",
            "unleashes a stinging volley of soft paddle strikes straight to {loser}'s warm, flushed cheeks",
            "secures {loser} face-down on the soft spanking bench, locking their waist strap with precision",
            "tears off {loser}'s satin robes, leaving them standing completely bare under the red chandelier",
            "locks a posture collar around {loser}'s neck, establishing complete playroom rules over their body",
            "runs a cold metal roller slowly along {loser}'s chest, keeping their senses on edge",
            "secures {loser}'s ankles to the high suspension pulley, raising their legs in complete exposure",
            "strips away {loser}'s lace stockings, leaving their bare feet and ankles cold and vulnerable",
            "locks {loser}'s wrists inside matching steel cuffs, clipping them directly to the overhead chain",
            "drips a single drop of warm organic oil onto {loser}'s bare shoulders, preparing them for the crop",
            "secures {loser} flat against the wooden cross, wrapping their chest in a tight velvet harness",
            "tears open {loser}'s buttoned corset, exposing their bare waist and ribs to the dim spotlight",
            "locks {loser}'s collar chain directly to the wall ring, keeping them completely locked on their knees",
            "runs a soft feather brush slowly along {loser}'s inner thighs, teasing their sensory limits",
            "secures {loser}'s hands inside padded leather mitts, leaving them completely unable to touch anything",
            "strips away {loser}'s delicate lace garter belt, exposing their bare hips on the leather cushions",
            "locks {loser} inside the padded sensory booth, turning off the lights to seal them in darkness",
            "unleashes a stinging slap with a wide leather paddle straight to {loser}'s flushed rear",
            "secures {loser}'s waist to the spanking horse, fastening the under-belly straps with a sharp snap",
            "tears open {loser}'s velvet shirt sleeves, exposing their bare arms to the cool air",
            "locks a heavy leather posture collar around {loser}'s throat, forcing their chin up in complete exposure",
            "runs a cold ice cube slowly along {loser}'s bare stomach, making them gasp dramatically",
            "secures {loser}'s ankles with matching velcro cuffs, linking them to their collar chain",
            "strips away {loser}'s final silk barrier, leaving them completely naked on the plush velvet sofa",
            "locks {loser}'s wrists to the heavy steel cross, ending all possibility of escape for the night",
            "drips warm lavender wax directly onto {loser}'s bare lower back, forcing a soft whimper",
            "secures {loser} face-down on the spanking bench, fastening the heavy leather straps with precision",
            "tears away {loser}'s satin slip, exposing their bare chest and stomach to the red spotlight",
            "locks {loser} inside the playroom cage, leaving them completely exposed to any passing dungeon guest",
            "runs a smooth glass rod slowly along {loser}'s inner thighs, raising goosebumps on their skin",
            "secures {loser}'s hands to the brass wall brackets, stretching their body in beautiful surrender",
            "strips away {loser}'s delicate lace garter, exposing their bare thighs to the cool dungeon breeze",
            "locks a posture collar around {loser}'s neck, forcing their chin up in complete and beautiful submission",
            "drips warm chamomile wax directly onto {loser}'s bare shoulders, making them gasp",
            "secures {loser} flat on the spanking horse, fastening the leather straps tight to ensure immobility",
            "tears off {loser}'s velvet gloves, leaving their bare hands trembling on the velvet cushions",
            "locks {loser} inside the iron wall chains, leaving them completely exposed to the master's next command",
            "runs a soft fur whip slowly down {loser}'s spine, sending intense shivers to their hips",
            "secures {loser}'s ankles with padded cuffs, linking them to the high suspension pulley",
            "strips away {loser}'s silk thigh-highs, leaving their bare legs completely vulnerable on the mattress",
            "locks {loser}'s hands behind their back with silk ties, ensuring absolute confinement",
            "unleashes a stinging volley of crop strikes right across {loser}'s bare rear",
            "secures {loser} face-down on the spanking horse, fastening the under-belly straps with precision",
            "tears off {loser}'s satin robes, exposing their bare chest and stomach to the red chandelier",
            "locks a posture collar around {loser}'s neck, claiming absolute playroom ownership over their body",
            "runs a cold metal wheel slowly along {loser}'s warm stomach, heightening their senses",
            "secures {loser}'s ankles to the wooden pillory, leaving them completely bare and surrendered",
            "strips away {loser}'s lace stockings, leaving their bare feet cold and vulnerable on the rug",
            "locks {loser}'s wrists inside steel shackles, clipping them directly to the overhead bar",
            "drips a drop of warm violet wax directly onto {loser}'s bare collarbone, making them gasp",
            "secures {loser} flat against the wooden cross, wrapping their body in tight rope coils",
            "tears open {loser}'s buttoned velvet shirt, leaving their warm chest entirely bare and exposed",
            "locks {loser}'s collar chain directly to the low floor ring, keeping them locked on their knees",
            "runs a soft feather brush slowly along {loser}'s ribs, teasing their sensory anticipation",
            "secures {loser}'s hands inside soft leather mitts, leaving them completely defenseless",
            "strips away {loser}'s velvet waistband, leaving their midsection completely bare and breathing rapidly",
            "locks {loser} inside the padded sensory cage, securing the heavy padlock with a click",
            "unleashes a sharp spank with a wide rubber paddle straight to {loser}'s warm, flushed cheeks",
            "secures {loser}'s waist to the spanking bench, locking their ankles to the floor rings below",
            "tears away {loser}'s delicate lace top, leaving their chest completely bare to the cool room air",
            "locks a heavy posture collar around {loser}'s throat, forcing their head back in complete exposure",
            "runs a smooth ice cube slowly down {loser}'s bare spine, forcing a broken, shaky whimper",
            "secures {loser}'s ankles with matching padded cuffs, linking them to the corner rings",
            "strips away {loser}'s silk underwear with a decisive pull, leaving them completely bare on the cushions",
            "locks {loser}'s wrists to the heavy steel cross, ending all remaining hope of escape",
            "drips warm lavender wax directly onto {loser}'s inner thighs, eliciting a sudden gasp",
            "secures {loser} face-down on the spanking horse, fastening the belly straps with a sharp snap",
            "tears open {loser}'s buttoned corset, exposing their bare waist and ribs under the dim red lights",
            "locks {loser} inside the heavy iron cage, securing them inside the playroom cell block for the night",
            "runs a cold steel wand slowly along {loser}'s ribs, sending light shivers through their chest",
            "secures {loser}'s hands to the wall brackets, keeping them completely locked in a vulnerable posture",
            "strips away {loser}'s lace-trimmed shorts, leaving their bare legs completely exposed to the room",
            "locks a posture collar around {loser}'s neck, establishing complete playroom rules over their body",
            "drips a single drop of warm organic oil onto {loser}'s neck, preparing their skin for the crop",
            "secures {loser} flat on the spanking horse, fastening the leather straps to ensure immobility",
            "tears off {loser}'s satin slip, exposing their bare chest and stomach under the hanging chandelier",
            "locks {loser} inside the private suspension frame, lifting them slowly off the ground into subspace",
            "runs a soft fur glove slowly along {loser}'s collarbone, heightening their sensory anticipation",
            "secures {loser}'s ankles to the heavy steel spreader bar, restricting their leg movement to zero",
            "strips away {loser}'s final silk barrier, leaving them completely bare and bound on the rug",
            "locks {loser}'s hands behind their back with velvet ties, securing them to the base of the throne",
            "unleashes a stinging strike with a carbon fiber crop right across {loser}'s warm thighs"
        ]

        # 2. Decretos de Strip / Humilhação Extrema
        self.humiliations: List[str] = [
            "Your resistance failed miserably. Shed every single piece of your clothing and accept your ultimate dungeon punishment.",
            "Caught red-handed and totally defenseless. Strip off your armor, show your submission, and kneel right now.",
            "No mercy for disobedient pets. Strip down completely on the cold leather mattress and expose your hot surrender.",
            "The Dominants have spoken. Hand over your pride, strip off those clothes, and bow down in complete submission.",
            "Bound in chains, bound in shame. The Master is coming, and you are caught totally bare. Start stripping!",
            "The playroom contract is signed and your body is owned. Strip down, kneel, and face your complete exposure.",
            "Your clothing is ours, your submission is ours. Take off those garments and let the chamber witness your sweet shame."
        ]

    def generate_fight_flavor(self, winner_name: Optional[str], loser_name: Optional[str]) -> str:
        """
        Gera uma narrativa de combate dinâmica de exatamente UMA frase coesa.
        """
        w_name = winner_name if winner_name else "Reigning Partner"
        l_name = loser_name if loser_name else "Defeated Outlaw"

        try:
            # Seleciona exatamente 1 frase da lista combinada
            action = random.choice(self.actions).format(loser=l_name)
            return f"💥 **{w_name}** {action}!"
        except Exception as e:
            logger.error(f"Failed to generate combat narrative: {e}")
            return f"💥 **{w_name}** completely overpowers **{l_name}** in a brutal showdown, claiming absolute victory!"

    def get_random_humiliation(self) -> str:
        """Retorna uma frase altamente temática de strip/humilhação do banco de dados."""
        try:
            return random.choice(self.humiliations)
        except Exception as e:
            logger.error(f"Failed to fetch random humiliation: {e}")
            return "Your heist failed. Pay the ultimate tax of complete exposure!"
