import random
import logging
from typing import List, Optional

# Configuração de Logger para sincronização e rastreio de geração de texto
logger = logging.getLogger("SyndicateLexicon")

class PartnersInCrimeLexicon:
    def __init__(self) -> None:
        # 1. Fase de Encontro Inicial (Dark Alley Encounters) - Total: 110 frases
        self.encounters: List[str] = [
            "corners {loser} against the leather-padded wall of the private dungeon...",
            "blindsides {loser} right outside the playroom, locking a heavy leather collar around their neck...",
            "intercepts {loser} as they try to creep away from the submissive bench, dragging them back by their cuffs...",
            "glares down {loser} with pure, dominant hunger beneath the dim red lights of the chamber...",
            "cuts off the exit door, backing {loser} up into a corner where the wooden spanking paddle hangs...",
            "ambushes {loser} while they are distracted, pinning their hands flat against the wooden cross...",
            "shoves {loser} roughly onto the soft leather mattress, placing a heavy knee onto their stomach...",
            "catches {loser} off-guard as they try to reach the safeword sign, tackling them down onto the soft fur rug...",
            "corrupts {loser}'s desperate resistance, blocking their retreat with a set of velvet ropes and silk blindfolds...",
            "pins {loser} face-first against the cold steel suspension frame...",
            "traps {loser} against the heavy wooden bondage wheel, snapping the leather straps around their wrists...",
            "lures {loser} into the center of the playroom, hooking their ankle cuffs to the floor ring...",
            "shadows {loser} beneath the structural beam of the dungeon ceiling, waiting for them to lower their guard...",
            "corners {loser} near the flogger display rack, taking away any room for escape...",
            "forces {loser} down onto the custom velvet kneeling cushion, boxing them in from behind...",
            "surprises {loser} as they try to sneak out of the sensory deprivation room, locking their hands in a soft leather muff...",
            "intercepts {loser} near the suspension pulley, sliding a soft silk rope loop over their wrists...",
            "ambushes {loser} near the dungeon dressing room, blocking their path with a set of metal collar keys...",
            "shoves {loser} back onto the high-backed master's chair, securing their arms to the carved armrests...",
            "catches {loser} off-guard near the wax play table, pinning their shoulders firmly to the tabletop...",
            "subdues {loser} beneath the soft glow of the hanging chandelier, sliding handcuffs onto their wrists...",
            "traps {loser} inside the padded sensory cage, locking the heavy brass latch with an ominous click...",
            "forces {loser} face-down onto the leather spanking bench, blocking any attempt to roll away...",
            "corners {loser} against the cold metal cage bars, fastening their hands high above their head...",
            "intercepts {loser} on the wooden catwalk, locking their wrists behind their back in one fluid movement...",
            "lures {loser} onto the heavy suspension platform, cutting off their gravity and control...",
            "ambushes {loser} near the playroom cabinet, sliding a thick leather blindfold over their eyes...",
            "pins {loser} against the heavy wooden pillory, snapping the lock shut over their neck and wrists...",
            "corners {loser} on the velvet sofa, leaning over them with absolute commanding authority...",
            "intercepts {loser} as they reach for the dungeon door handle, spinning them around to lock them against the timber...",
            "glares at {loser} from across the dark playroom, slowly clicking the handcuffs open in warning...",
            "cuts off {loser}'s retreat to the safe area, backing them into the sensory-play corner...",
            "forces {loser} onto all fours on the soft sheepskin rug, stepping lightly on the chain of their collar...",
            "traps {loser} against the wooden St. Andrew's cross, securing their limbs with swift rope wraps...",
            "pins {loser} on the examination table, securing their ankles to the steel Stirrups...",
            "catches {loser} off-guard during a moment of hesitation, snapping tight velcro cuffs around their ankles...",
            "lures {loser} into the master bedroom, locking the door to establish absolute playroom rules...",
            "ambushes {loser} near the restraint rack, sliding a thick padded collar around their throat...",
            "shoves {loser} against the mirrored wall, forcing them to look at their own helpless posture...",
            "blocks {loser} as they try to crawl to safety, pinning them down on the leather mattress...",
            "corners {loser} near the leather whipping post, securing their hands to the heavy brass eyelets...",
            "intercepts {loser} under the red spotlight, sliding a cold metal chain through their belt loops...",
            "shadows {loser} through the dim hallways of the club, cornering them in the private master suite...",
            "surprises {loser} near the velvet swing, pushing them back until they are completely off-balance...",
            "forces {loser} to kneel before the throne chair, securing their wrists to the base of the frame...",
            "traps {loser} in the corner of the dungeon, blocking their vision with a smooth neoprene hood...",
            "pins {loser} against the brick pillar, wrapping a heavy leather strap around their waist...",
            "catches {loser} off-guard near the toy chest, locking their fingers in soft leather mitts...",
            "lures {loser} onto the suspension frame, adjusting the pulley system to keep them slightly off the ground...",
            "ambushes {loser} as they try to adjust their gear, locking a neck-to-wrist harness onto their body...",
            "shoves {loser} onto the spanking horse, fastening the under-belly straps with a sharp snap...",
            "blocks {loser}'s escape route to the door, forcing them to back up toward the restraint table...",
            "corners {loser} against the heavy wooden chest, pinning their hands flat against the lid...",
            "intercepts {loser} beneath the suspension rings, hooking their wrist restraints to the overhead chain...",
            "lures {loser} into the master playroom, setting the padlock keys on a high shelf out of reach...",
            "ambushes {loser} from the shadows, sliding a soft silicone gag over their lips before they can make a sound...",
            "pins {loser} against the plush leather headboard, handcuffing them to the brass posts...",
            "catches {loser} off-guard in the velvet parlor, locking a heavy metal collar around their neck...",
            "forces {loser} down onto the cold marble pedestal, securing their arms behind their back...",
            "traps {loser} near the flogger display, pinning their hips to the wooden support beam...",
            "corners {loser} under the hanging ropes, sliding a soft velvet blindfold over their face...",
            "intercepts {loser} near the cage entrance, pushing them back into the dark interior...",
            "shadows {loser} to the restraint chair, locking the leather wrist straps with absolute precision...",
            "surprises {loser} by the fireplace, wrapping a soft leather leash around their hand...",
            "forces {loser} onto the submissive bench, hooking their cuffs to the built-in D-rings...",
            "traps {loser} against the wooden cross, wrapping their chest in a tight, securing harness...",
            "pins {loser} to the floor of the playroom, securing their ankles with heavy leather straps...",
            "catches {loser} off-guard as they adjust their clothing, sliding their arms into a posture collar...",
            "lures {loser} into the private sensory booth, turning off the lights to seal them in darkness...",
            "ambushes {loser} near the whip rack, sliding a thick leather belt around their chest...",
            "shoves {loser} onto the plush leather bolster, locking their hands in matching wrist cuffs...",
            "blocks {loser} as they attempt to stand, pushing them back down onto their knees...",
            "corners {loser} near the suspension pulley, snapping the carabiners onto their wrist restraints...",
            "intercepts {loser} near the vanity mirror, pinning their hands against the glass...",
            "lures {loser} onto the heavy dungeon platform, locking their restraints to the corner rings...",
            "ambushes {loser} on the velvet carpet, sliding a soft neoprene mask over their head...",
            "pins {loser} to the wooden workbench, securing their wrists with soft cotton ropes...",
            "catches {loser} off-guard by the book case, snapping a padlock onto their collar chain...",
            "forces {loser} down onto the leather spanking horse, fastening their ankles to the floor rings...",
            "traps {loser} inside the iron cage, sliding the heavy padlock into place with a definitive click...",
            "corners {loser} behind the velvet curtains, securing their hands behind their back with silk ties...",
            "intercepts {loser} as they crawl near the footstool, locking their wrists in padded cuffs...",
            "shadows {loser} near the suspension cross, clipping their harness to the main steel ring...",
            "surprises {loser} by the play table, wrapping a soft leather restraint around their torso...",
            "forces {loser} onto the master's footrest, placing a firm hand on their shoulder...",
            "traps {loser} against the brick chimney, sliding a posture harness over their shoulders...",
            "pins {loser} to the padded examination board, securing their legs in matching loops...",
            "catches {loser} off-guard near the candle rack, securing their hands to the wall brackets...",
            "lures {loser} onto the leather chaise lounge, locking their wrists to the brass feet...",
            "ambushes {loser} near the sensory drawer, sliding a soft silicone gag into place...",
            "shoves {loser} against the heavy timber pillar, securing their arms around the wood...",
            "blocks {loser}'s retreat near the cage door, snapping leather cuffs onto their ankles...",
            "corners {loser} near the plush sofa, pinning their hands to the velvet cushions...",
            "intercepts {loser} near the suspension apparatus, hooking their ankle cuffs to the spreader bar...",
            "lures {loser} into the private cellar playroom, locking the reinforced oak door behind them...",
            "ambushes {loser} from behind the wooden cross, sliding a silk blindfold over their eyes...",
            "pins {loser} to the leather table, wrapping their torso in soft, securing rope coils...",
            "catches {loser} off-guard near the padlock case, securing their wrists with a quick-zip strap...",
            "forces {loser} down onto the soft fur mattress, pinning their arms above their head...",
            "traps {loser} inside the wooden pillory, securing the latch with a polished brass lock...",
            "corners {loser} near the dungeon mirror, locking their posture collar with a key...",
            "intercepts {loser} near the velvet swing, clipping their wrist straps to the support chain...",
            "shadows {loser} to the spanking bench, securing their waist strap to the frame...",
            "surprises {loser} near the leather armchair, locking their hands behind their back...",
            "forces {loser} onto their knees on the polished floor, hooking their collar to the floor ring...",
            "traps {loser} against the heavy wooden wheel, securing their ankles with padded cuffs...",
            "pins {loser} to the massage table, wrapping their arms in soft velvet restraint loops...",
            "catches {loser} off-guard near the playroom cabinet, sliding a soft leather gag over their lips...",
            "lures {loser} into the corner of the dungeon, securing their hands to the low wall rings...",
            "ambushes {loser} near the main suspension frame, clipping their ankle cuffs to the high pulley..."
        ]

        # 2. Fase de Ataque (Aggressive NSFW Strikes) - Total: 110 frases
        self.attacks: List[str] = [
            "rips off their lace harness, exposing their shivering, sensitive bare chest",
            "strips away their silk robe, leaving them entirely defenseless, shivering, and exposed",
            "unleashes a stinging volley of leather crop strikes straight to their tender thighs",
            "swipes low with a soft feather tickler, slicing cleanly through their sensory defenses",
            "tears off their restraint straps, scattering their blindfolds and gags across the floor",
            "grabs them roughly by their leather collar, forcing them onto their knees in complete submission",
            "disarms their willpower completely with a tight, inescapable rope wrap around their torso",
            "presses a freezing metal ice cube directly against their warm, exposed throat",
            "slams a heavy leather paddle onto their bare skin, sending burning waves of pleasure and pain through their body",
            "shoves a silicone ball gag between their lips, muffling their gasps into absolute submission",
            "unbuckles their leather corset, leaving their chest completely bare and breathing heavily",
            "traces a cold metal flogger slowly along their ribs, sending intense shivers down their spine",
            "rips open their buttoned velvet shirt, exposing their warm chest to the cool dungeon air",
            "unleashes a series of rhythmic spanks with a heavy rubber paddle, heating up their skin",
            "strips away their lace stockings, leaving their bare legs completely vulnerable and cold",
            "slides a smooth feather duster across their lower back, teasing their sensory nerves",
            "tightens the leather straps on their posture collar, forcing their chin up in complete exposure",
            "unbuckles their thigh-high boots, leaving their bare feet and ankles completely exposed",
            "presses a warm candle-wax bottle against their inner thigh, preparing them for the heat",
            "pulls their arms back with a soft rope pulley, stretching their chest in complete submission",
            "strips away their satin briefs with a single, commanding pull, leaving them completely exposed",
            "unleashes a sharp, stinging slap with a wide suede paddle straight to their flushed cheeks",
            "runs a cold metal wheel over their bare skin, raising goosebumps along their sensitive thighs",
            "tears away their delicate lace top, leaving their chest entirely exposed under the red lights",
            "squeezes their waist with a heavy leather harness, restricting their movement completely",
            "applies a pair of soft, velvet-lined clamps to their sensitive areas, raising the tension",
            "swipes low with a soft fur paddle, combining soft touch with a heavy, stinging blow",
            "strips their silk blindfold away, forcing them to look directly into their Dominant's eyes",
            "tightens the ropes around their chest, defining their vulnerability under the play room lights",
            "presses a soft velvet strap over their mouth, keeping their soft whimpers completely contained",
            "traces a warm glass rod slowly across their bare stomach, heightening their sensory awareness",
            "rips off their leather vest, exposing their bare, flushed shoulders to the cool air",
            "unleashes a stinging strike with a thin carbon crop right across their rear",
            "strips away their lace-up trousers, leaving their bare thighs completely exposed on the leather mattress",
            "pulls their wrists closer to their collar with a short steel connector chain, restricting their posture",
            "slides a heavy leather blindfold over their eyes, plunging their world into complete sensory darkness",
            "slams a wide wooden ruler against their lower back, leaving a warm, red glow behind",
            "tears away their satin undershirt, leaving their skin completely bare and trembling",
            "applies a drop of warm, skin-safe lavender wax directly to their bare collarbone",
            "unbuckles their leather thigh straps, stripping away their final defense line",
            "traces a soft fur whip slowly along their spine, sending intense shivers down to their hips",
            "tightens the leather handcuffs around their wrists, cutting off any remaining slack",
            "strips away their delicate lace garter belt, exposing their bare hips in complete submission",
            "unleashes a sharp volley of soft slaps with a leather spanking glove across their skin",
            "presses a vibrating sensory toy against their bare, sensitive stomach, shattering their control",
            "rips open their satin robes, leaving them standing completely bare under the red chandelier",
            "unbuckles their heavy waist belt, leaving their hips completely free and defenseless",
            "runs a smooth ice cube slowly down their spine, leaving a trail of freezing water on their warm skin",
            "tears off their silk scarf, exposing their bare neck and collarbone to the cold steel collar",
            "applies a pair of adjustable magnetic clamps to their chest, increasing the physical focus",
            "unleashes a stinging strike with a split-strap leather paddle across their lower thighs",
            "strips away their mesh top, exposing their shivering chest to the gaze of the room",
            "traces a heavy metal key slowly across their lower stomach, teasing their sensory limits",
            "tightens the ropes around their thighs, forcing them to hold a submissive, kneeling posture",
            "squeezes a soft sponge filled with cold water over their bare shoulders, causing them to shiver",
            "rips away their velvet sash, leaving their midriff completely bare and exposed",
            "unbuckles their shoulder harness, letting all their gear drop to the playroom floor",
            "unleashes a rhythmic spanking with a soft leather paddle, keeping their skin warm and flushed",
            "strips away their lace-trimmed shorts, leaving their bare legs completely exposed to the room",
            "presses a warm massage stone slowly against their inner thigh, heating up their senses",
            "tears open their buttoned corset, exposing their bare waist and ribs to the cold air",
            "traces a sharp fingernail slowly across their bare chest, leaving light pink marks behind",
            "tightens the leather ankle straps, locking them in a wide, vulnerable posture",
            "strips away their silk underwear with a decisive pull, leaving them completely naked on the rug",
            "unleashes a stinging strike with a soft silicone paddle right across their lower back",
            "applies a soft velvet blindfold over their eyes, sealing their vision in complete darkness",
            "runs a cold metal roller slowly along their inner thigh, heightening their anticipation",
            "rips off their lace harness, leaving their sensitive skin completely bare and flushing",
            "unbuckles their chest restraint, forcing their shoulders back in complete exposure",
            "presses a soft leather gag between their lips, securing the buckle behind their head",
            "tears away their satin slip, exposing their bare chest and stomach to the red spotlight",
            "unleashes a stinging volley of light whip strikes straight to their lower back",
            "strips away their velvet gloves, leaving their bare hands trembling and defenseless",
            "traces a soft feather brush slowly along their collarbone, teasing their sensory nerves",
            "tightens the ropes around their ankles, restricting their movement to absolute zero",
            "squeezes a drop of warm violet wax directly onto their bare shoulder, making them gasp",
            "rips off their leather collar leash, pulling them closer to the master's chair",
            "unbuckles their leg restraints, leaving them completely free to feel the cool room air",
            "unleashes a sharp slap with a wide leather paddle straight to their warm thighs",
            "strips away their delicate lace trim, exposing their bare skin to the playroom lights",
            "presses a cold metal coin slowly against their warm, sensitive neck",
            "tears open their satin shirt, leaving their chest entirely bare and breathing rapidly",
            "traces a soft silicone crop slowly along their ribs, sending light shivers through their body",
            "tightens the leather wrist cuffs, leaving absolutely no room for struggle",
            "strips away their silk thigh-highs, leaving their bare legs completely vulnerable on the mattress",
            "unleashes a stinging volley of flogger strikes across their lower back",
            "applies a pair of padded leather clamps to their chest, locking in the physical sensation",
            "runs a warm glass rod slowly down their bare stomach, keeping their senses on edge",
            "rips away their velvet waistband, leaving their midsection completely bare and exposed",
            "unbuckles their ankle harness, letting their legs fall into a wide, submissive position",
            "presses a soft silicone toy against their bare thigh, sending intense vibrations through their body",
            "tears off their lace bralette, exposing their bare chest to the cool dungeon air",
            "unleashes a sharp, ringing spank with a heavy leather paddle straight to their rear",
            "strips away their satin robe sleeves, leaving their bare shoulders completely exposed",
            "traces a cold steel wand slowly along their spine, raising goosebumps along their skin",
            "tightens the rope harness around their chest, making every breath highly visible",
            "squeezes a drop of warm organic oil onto their bare neck, preparing them for the touch",
            "rips away their lace-up corset strings, exposing their warm chest to the dim room lights",
            "unbuckles their leather belt restraint, letting their lower garments fall to the floor",
            "unleashes a stinging strike with a soft leather crop straight to their inner thighs",
            "strips away their final silk barrier, leaving them completely naked and vulnerable on the velvet cushions",
            "presses a cold ice cube slowly against their bare, sensitive stomach",
            "tears off their satin blindfold, forcing them to witness their own bound posture in the mirror",
            "traces a soft fur glove slowly along their collarbone, heightening their sensory anticipation",
            "tightens the leather collar around their throat, establishing complete playroom rules",
            "unleashes a stinging volley of soft paddle strikes across their flushed skin",
            "applies a drop of warm skin-safe wax directly to their bare lower back",
            "strips away their lace garter, exposing their bare thighs to the cool dungeon breeze",
            "pulls their bound wrists upward with the suspension rope, stretching their chest in complete exposure"
        ]

        # 3. Fase de Defesa (Defense & Counter Struggles) - Total: 110 frases
        self.defenses: List[str] = [
            "forcing them to whimper and plead for their Dominant's split-second mercy!",
            "leaving them completely bare, trembling and blushing under the dark dungeon spotlights!",
            "nearly tearing their remaining lace undergarments to absolute shreds!",
            "making them gasp desperately for air as their wrists are bound tightly behind their back!",
            "forcing them to surrender their pride and show their completely exposed, helpless state!",
            "crying out in helpless surrender as they try in vain to cover their sensitive body!",
            "leaving them shivering, flushed, and utterly vulnerable to the next stinging strike!",
            "letting out an embarrassing, high-pitched gasp as their last piece of clothing falls away!",
            "making them beg their partner for a safeword that will absolutely never be granted!",
            "forcing them flat onto their belly, utterly bound and surrendered on the padded bench!",
            "forcing a broken whimper out of them as their bare skin touches the freezing, wet industrial asphalt!",
            "leaving them completely exposed and gasping for breath under the heavy, dominating weight of their captor!",
            "tearing their remaining clothing to absolute ribbons, revealing every inch of their flushed, sensitive skin!",
            "making them writhe in desperate, helpless arousal as their wrists are bound tightly with steel wire!",
            "leaving them shivering in complete, naked vulnerability under the glaring beam of the surveillance spotlight!",
            "forcing them to display their complete defeat as their intimate gear is systematically stripped away!",
            "making them let out a high-pitched cry of surrender as their final defense line is broken and exposed!",
            "leaving them totally defenseless, trembling with heat and fear as they are pressed flat against the cold brick wall!",
            "forcing them to beg their conquerors to stop the merciless, teasing exposure!",
            "leaving them utterly bound, exposed, and stripped of any remaining outlaws' dignity!",
            "forcing a deep, shaky sigh from their chest as the leather paddle connects with their skin!",
            "leaving them completely bare, writhing in helpless pleasure on the soft fur rug!",
            "nearly tearing their delicate lace harness to absolute pieces under the heavy pressure!",
            "making them gasp for breath as the cold metal chains are locked around their waist!",
            "forcing them to surrender their voice, their soft groans muffled by the silicone gag!",
            "screaming out in pure sensory overload as the cold ice cube melts against their stomach!",
            "leaving them shivering, exposed, and completely at the mercy of their Master's next command!",
            "letting out an embarrassing Whimper as the last satin thread is cut from their body!",
            "making them beg for a brief pause that their Dominant completely ignores with a smile!",
            "forcing them flat onto the leather examination table, completely surrendered to the ropes!",
            "forcing a soft, breathless plea from their lips as the warm candle wax drops onto their chest!",
            "leaving them completely vulnerable, their flushed face hidden behind a dark silk blindfold!",
            "tearing their lace underwear to absolute shreds, exposing their sensitive skin to the cool air!",
            "making them writhe against the wooden cross, the tight ropes keeping them perfectly in place!",
            "leaving them shivering in naked, submissive posture under the low hanging red spotlight!",
            "forcing them to display their complete lack of control as their hands are locked behind them!",
            "making them let out a shaky gasp of submission as the leather crop strikes their thighs!",
            "leaving them totally defenseless, their body trembling with heat under the heavy flogger!",
            "forcing them to beg their partner for a mercy they have absolutely no intention of showing!",
            "leaving them utterly bound, exposed, and stripped of any remaining pride on the leather bench!",
            "forcing a broken whimper out of them as the velvet-lined clamps are tightened on their chest!",
            "leaving them completely bare, trembling with sweet anticipation under the Master's gaze!",
            "nearly tearing their remaining lace stockings to absolute ribbons during the struggle!",
            "making them gasp for air as the posture collar forces their chin up toward the ceiling!",
            "forcing them to surrender their mobility, their legs secured wide by the leather spreader bar!",
            "crying out in helpless arousal as the smooth feather duster traces along their inner thighs!",
            "leaving them shivering, flushed, and utterly defenseless under the heavy leather harness!",
            "letting out an embarrassing moan of pleasure as the soft paddle strikes their sensitive skin!",
            "making them beg their captor for a touch that is teasingly withheld from them!",
            "forcing them flat onto their stomach, their wrists padlocked securely to the floor rings!",
            "forcing a soft whimper from their throat as the cold steel wheel runs down their spine!",
            "leaving them completely exposed, their sensitive skin blushing deep red under the spotlights!",
            "tearing their satin lingerie to absolute shreds, leaving them completely naked on the sofa!",
            "making them writhe in helpless frustration as the wrist shackles hold them tight to the post!",
            "leaving them shivering in naked, breathless submission as the cold water drops onto their shoulders!",
            "forcing them to show their complete submission as their collar leash is pulled tight!",
            "making them let out a high-pitched sigh of relief as the heavy spanking paddle stops!",
            "leaving them totally defenseless, their hands secured firmly in the soft leather mitts!",
            "forcing them to beg for their Dominant's touch as the sensory blindfold limits their world!",
            "leaving them utterly bound, exposed, and surrendered on the plush velvet cushions!",
            "forcing a deep whimper from their chest as the warm massage stones touch their thighs!",
            "leaving them completely bare, their body flushing with warmth under the red dungeon lights!",
            "nearly tearing their delicate silk robe to absolute pieces as it is yanked away!",
            "making them gasp for breath as the leather strap is tightened around their waist!",
            "forcing them to surrender their protests, their lips sealed by the smooth silicone gag!",
            "crying out in helpless surrender as the cold steel chain touches their bare hips!",
            "leaving them shivering, flushed, and completely vulnerable to the next stroke of the crop!",
            "letting out an embarrassing gasp as their lace bralette is cut from their chest!",
            "making them beg for a release that will only come when their submission is complete!",
            "forcing them flat onto the massage table, their limbs secured by the padded restraints!",
            "forcing a soft, shaky whimper from their lips as the warm lavender wax drops onto their skin!",
            "leaving them completely vulnerable, their wrists bound tightly to the overhead suspension ring!",
            "tearing their satin briefs to absolute ribbons, exposing their flushed skin to the room!",
            "making them writhe against the heavy wooden cross, their chest rising and falling rapidly!",
            "leaving them shivering in naked, submissive posture under the low hanging red spotlight!",
            "forcing them to display their complete defeat as their intimate gear is stripped away!",
            "making them let out a shaky sigh of surrender as the heavy leather paddle warms their skin!",
            "leaving them totally defenseless, their eyes covered by the thick leather blindfold!",
            "forcing them to beg for a drop of water that their Dominant holds just out of reach!",
            "leaving them utterly bound, exposed, and surrendered on the cold leather bench!",
            "forcing a broken whimper out of them as the adjustable clamps are tightened on their chest!",
            "leaving them completely bare, trembling with sweet anticipation under the Master's gaze!",
            "nearly tearing their remaining lace undergarments to absolute shreds during the play!",
            "making them gasp for air as the posture collar forces their head back in complete exposure!",
            "forcing them to surrender their pride, their wrists locked tightly in the heavy iron cuffs!",
            "crying out in helpless arousal as the fur whip traces along their warm thighs!",
            "leaving them shivering, flushed, and utterly defenseless under the heavy leather harness!",
            "letting out an embarrassing moan as the spanking glove strikes their sensitive skin!",
            "making them beg their partner for a touch that is teasingly denied to them!",
            "forcing them flat onto the padded platform, their ankles secured to the high pulley!",
            "forcing a soft whimper from their throat as the cold ice cube melts down their chest!",
            "leaving them completely exposed, their sensitive skin blushing deep red under the spotlights!",
            "tearing their satin chemise to absolute shreds, leaving them completely naked on the rug!",
            "making them writhe in helpless frustration as the wrist shackles hold them tight to the post!",
            "leaving them shivering in naked, breathless submission as the warm wax drops onto their hips!",
            "forcing them to show their complete submission as their collar chain is pulled tight!",
            "making them let out a high-pitched sigh of relief as the flogger strikes finally stop!",
            "leaving them totally defenseless, their hands secured firmly in the velvet mitts!",
            "forcing them to beg for their Dominant's approval as the sensory hood limits their world!",
            "leaving them utterly bound, exposed, and surrendered on the soft fur mattress!",
            "forcing a deep whimper from their chest as the warm massage stones touch their shoulders!",
            "leaving them completely bare, their body flushing with warmth under the red dungeon lights!",
            "nearly tearing their delicate silk scarf to absolute pieces as it is yanked away!",
            "making them gasp for breath as the leather belt is tightened around their chest!",
            "forcing them to surrender their protests, their lips sealed by the soft silicone gag!",
            "crying out in helpless surrender as the cold key traces along their bare hips!",
            "leaving them shivering, flushed, and completely vulnerable to the next stroke of the paddle!",
            "letting out an embarrassing gasp as their lace bralette is stripped from their chest!",
            "making them beg for a release that will only come when their submission is complete!",
            "forcing them flat onto the spanking horse, their limbs secured by the under-belly straps!"
        ]

        # 4. Fase de Transição (Environmental Transitions) - Total: 108 frases
        self.evasions: List[str] = [
            "Low-frequency dungeon music echoes through the chamber, multiplying the hot tension.",
            "Warm wax drops slowly from the ceiling candles, keeping their exposed skin highly sensitive.",
            "Deep crimson lights pulse aggressively, painting their desperate struggles in shades of ruby and pink.",
            "The heavy scent of premium leather, lavender oil, and heated skin hangs thick in the air.",
            "There is absolutely no escape left for submissives once the dungeon door is locked from the outside.",
            "The multi-angle security cameras record every single second of their delicious, humiliating defeat.",
            "Dominants watch from behind the tinted glass, whispering and laughing at the total lack of dignity.",
            "The cold steel of the wrist shackles cuts off any remaining illusion of control.",
            "Thick steam escapes from the underground heating pipes, covering their bound bodies in hot, damp mist.",
            "The intercom cracks with static as the master of ceremonies announces the next playtime rotation.",
            "The main dungeon lights fade out completely, leaving them illuminated only by the warm glow of wax candles.",
            "A heavy leather curtain sweeps closed across the play area, isolating them from the rest of the club.",
            "Heavy bass rumbles from the dance floor upstairs, shaking the timber foundations of the private playroom.",
            "The soft chime of a brass bell echoes through the hall, signaling that their time of submission has begun.",
            "A cool draft sweeps through the dungeon floor, making their exposed, damp skin shiver intensely.",
            "The low hum of the air ventilation system keeps the scent of leather and oil circulating through the room.",
            "A red laser line sweeps across the floor, marking the boundary of the master's private play space.",
            "The distinct sound of a leather whip cracking in the adjacent room raises the tension to its peak.",
            "Soft classical music begins to play from the hidden speakers, contrastingly highlighting their heavy gasps.",
            "The clicking sound of a high heel heel on the concrete floor echoes, signaling the master's approach.",
            "Damp mist rises from the floor drains, wrapping their bound legs in a thin, cold fog.",
            "A sudden flash of a camera from the viewing gallery captures their helpless, bound posture.",
            "The scent of burning sandalwood incense fills the air, adding an exotic layer to the playroom sensory experience.",
            "The master's heavy keys jingle softly as they are set down on the small table next to the bench.",
            "The electronic collar around their neck gives a soft, warning beep, reminding them of the playroom boundaries.",
            "A sudden silence falls over the dungeon floor as the heavy oak doors are bolted from the inside.",
            "The shadow of a leather whip is projected onto the wall, dancing under the flickering candle light.",
            "The soft hum of a mechanical toy begins to vibrate through the floorboards, raising their anticipation.",
            "The cool metal of the bondage cross presses against their back, reminding them of their lack of movement.",
            "A drop of scented water falls from the ceiling, landing directly on their bare, sensitive shoulder.",
            "The rhythmic creaking of the wooden suspension beam overhead echoes through the quiet room.",
            "The dim red neon sign on the wall flickers twice, painting their skin in deep shades of crimson.",
            "A warm breeze from the heating vent sweeps across the mattress, drying the sweat on their bare skin.",
            "The heavy scent of leather wax and polish rises from the master's boots, filling the air.",
            "The soft rustling of latex sheets on the massage table next to them adds a sharp sensory detail.",
            "The countdown timer on the wall-mounted screen ticks down slowly, marking the remaining playtime.",
            "A sudden shadow falls over the playroom as the main spotlight is directed straight at their bench.",
            "The metallic click of a padlock closing on the adjacent cage echoes, sending a shiver through their spine.",
            "The scent of fresh rain from the ventilation shaft mixes with the warm wax aroma in the room.",
            "The master's leather crop is tapped rhythmically against their open palm, creating a steady, tense beat.",
            "The low hum of the neon lights overhead vibrates through the quiet, red-lit playroom.",
            "A soft, velvet rope is pulled tight across the entrance, indicating that their session is completely private.",
            "The distinct sound of ice clinking in a glass next to the bed breaks the silence of the playroom.",
            "A warm, damp towel is placed on the table next to them, sending steam up into the cool air.",
            "The sound of heavy breathing from the neighboring booth highlights the intense focus of the dungeon.",
            "The master's leather collar is adjusted with a sharp snap of the buckle, locking in their role.",
            "A sudden draft from the corridor makes the candle flames flicker aggressively, shifting the shadows.",
            "The metallic scent of steel chains and iron cages hangs heavy in the damp cellar air.",
            "The soft, rhythmic squeak of the leather suspension pulley overhead marks their slow movement.",
            "The red spotlight shifts slowly, focusing entirely on their bound wrists and flushed chest.",
            "The sound of a heavy wooden door sliding shut locks out any remaining connection to the outside world.",
            "The scent of expensive leather conditioner rises from the padded bench, filling their senses.",
            "A soft leather blindfold is adjusted over their eyes, shifting their focus entirely to touch and sound.",
            "The ticking of a large mechanical clock on the wall provides a steady, relentless beat to their submission.",
            "A sudden drop in temperature makes their bare, sensitive skin react instantly with goosebumps.",
            "The low hum of the bass from the main lounge vibrates through the reinforced concrete walls.",
            "The sound of the master's leather whip being uncoiled from the hook raises their heart rate.",
            "The scent of vanilla wax and warm oils fills the immediate air around the play mattress.",
            "A sudden flash of light from the doorway sweeps across the room as a new guest is admitted.",
            "The soft, metallic jingle of the key ring indicates that their locks are about to be tested.",
            "The rhythmic creaking of the velvet swing chains overhead adds a steady soundtrack to their struggle.",
            "The red neon light on the ceiling casts a warm, soft glow over their exposed, flushing skin.",
            "The sound of a heavy book of dungeon rules being opened on the table next to them adds a formal tone.",
            "A cool glass of water is set down next to their head, the condensation dripping slowly onto the wood.",
            "The scent of fresh lavender and warm wax creates a calming yet highly intense playroom atmosphere.",
            "The distinct sound of a leather paddle hitting a soft surface in the next room echoes clearly.",
            "The low-frequency vibration of the subwoofers under the floorboards keeps their body on edge.",
            "A sudden shadow blocks out the light from the corridor as the master takes their position.",
            "The metallic click of the carabiner connecting their cuffs to the chain is loud in the quiet room.",
            "The warm, thick scent of leather polish and heated skin rises from the spanking bench.",
            "The soft rustling of silk ropes being coiled on the floor adds a classic bondage sound to the room.",
            "The red spotlight dims slowly, leaving them in near complete darkness except for a single beam.",
            "The sound of a heavy padlock sliding into the iron hasp of the door locks them in for the night.",
            "The scent of ozone and warm electrical equipment from the sensory devices hangs in the air.",
            "The rhythmic ticking of the master's pocket watch is a quiet reminder of their ongoing penalty.",
            "A cool breeze from the wall-mounted fan sweeps across their bare back, making them shiver.",
            "The sound of a leather harness being buckled onto the master's frame indicates play is about to resume.",
            "The soft hum of the humidifier fills the room with a gentle, continuous mist of lavender.",
            "A sudden draft from the open door makes the shadows on the brick wall dance aggressively.",
            "The heavy, sweet scent of burning honey and warm wax rises from the decorative candles.",
            "The distinct sound of a spanking glove being pulled onto a hand creates a sharp, snapping noise.",
            "The low-frequency hum of the building's main generator keeps a steady vibration in the floor.",
            "A red laser line sweeps slowly across their bound chest, marking the target for the next strike.",
            "The sound of heavy leather boots walking slowly around the suspension cross raises their anticipation.",
            "The scent of premium leather conditioner and heated wax rises from the examination table.",
            "The soft rustling of a silk blindfold being tied behind their head cuts off their final visual anchor.",
            "The metallic jingle of the spreader bar chains indicates that their posture is about to be adjusted.",
            "The dim red spotlight focuses directly on their bound ankles, highlighting their complete submissive stance.",
            "The sound of a sliding wooden partition door isolates their private play space from the main hallway.",
            "The scent of burning amber incense fills the air, creating a rich, intoxicating play environment.",
            "The rhythmic creaking of the leather spanking horse under their weight adds a steady sound to the room.",
            "A sudden drop in the music's volume highlights the sound of their own rapid, shallow breathing.",
            "The metallic click of the safety latch on the suspension pulley ensures their position is locked.",
            "The warm, rich scent of coconut oil and heated wax rises from the play mattress.",
            "The soft rustling of a feather duster being picked up from the tray sends a shiver of anticipation.",
            "The red neon sign above the door glows steadily, indicating that their private session is active.",
            "The sound of a heavy leather whip being tapped against the timber post echoes through the room.",
            "The low hum of the air conditioner keeps the room at a crisp, contrasting temperature to their warm skin.",
            "A sudden shadow falls over their blindfold as the master stands directly in front of the bench.",
            "The metallic jingle of the ankle chains on the spreader bar is loud in the quiet playroom.",
            "The scent of fresh cotton ropes and leather wax rises from the bondage tray next to the cross.",
            "The rhythmic ticking of the dungeon's mechanical clock is the only sound during the quiet intervals.",
            "A cool draft from the floor level makes their bare, bound ankles shiver against the steel rings.",
            "The sound of a leather collar being buckled onto their neck marks the official start of the scene.",
            "The soft hum of the neon light over the mirror adds a steady, continuous vibration to the room.",
            "A sudden flash of the emergency strobe indicates a temporary power shift on the main grid.",
            "The heavy, rich scent of leather and heated skin rises from the private master parlor.",
            "The distinct sound of a flogger hitting the wooden cross frame echoes clearly through the silence."
        ]

        # 5. Golpes de Misericórdia (Finisher Executions) - Total: 108 frases
        self.finishers: List[str] = [
            "delivers a devastating flurry of flogger strikes, stripping away every single piece of their remaining garments!",
            "snaps heavy steel padlocks around their wrist chains, demanding their complete and absolute surrender!",
            "completely overpowers their senses, forcing them into a state of absolute, heavy subspace!",
            "neutralizes their desperate struggle, leaving them completely naked, bound, and blindfolded!",
            "claims their total sensory tribute, leaving them breathless, exposed, and entirely at their Master's mercy!",
            "forces them to sign the submissive contract with a cold metal whip handle pressed hard against their bare back!",
            "drags them kicking and whimpering into the dark VIP playroom for their private punishment!",
            "neutralizes their defenses completely, making them submit to the ultimate, breathless dungeon exposure!",
            "shackles their ankles to the steel suspension ring, leaving them completely bare and suspended in the air!",
            "locks a heavy leather posture collar around their neck, claiming absolute playroom ownership over their body!",
            "slams their hands into the matching wall restraints, forcing them to watch their own naked surrender in the mirror!",
            "confiscates all their remaining clothing and pride, leaving them stripped, bound, and kneeling on the rug!",
            "marks their bare, flushed skin with a soft, warm wax seal of complete submissive dedication!",
            "forces them to bow down before the master's throne, placing a heavy leather boot on their bound hands!",
            "locks them in the iron playroom cage, leaving them completely exposed to any passing dungeon guest!",
            "delivers a final, merciless spanking with a wide leather paddle, leaving them standing bare under the red lights!",
            "snaps a cold metal collar around their neck, hooking the leash to the high suspension pulley with a click!",
            "completely binds them from chest to ankle in tight rope coils, leaving them helpless on the soft mattress!",
            "neutralizes their final struggle with a soft silicone gag, securing their complete and silent submission!",
            "claims their total willpower, forcing them to kneel and kiss the master's leather boots in surrender!",
            "drags them by their collar leash straight into the private master suite for their final, personal scene!",
            "neutralizes their defenses with a heavy leather blindfold, sealing their world in complete submissive darkness!",
            "shackles their wrists behind their back to the heavy steel cross, ending all possibility of escape!",
            "locks their ankles in the wooden pillory, leaving them completely bare and surrendered to the room!",
            "slams the cage door shut and snaps the heavy padlock into place, securing their submissive role for the night!",
            "delivers a final, stinging crop strike across their thighs, marking them as the playroom's favorite pet!",
            "forces them into a complete suspension harness, lifting them slowly off the ground into absolute subspace!",
            "snaps heavy velcro cuffs around their limbs, binding them securely to the four corners of the bed!",
            "completely strips away their remaining defenses, leaving them standing bare and bound in the center of the room!",
            "claims their final submission, locking their collar chain to the heavy iron ring on the wall!",
            "drags them to the spanking horse, fastening the leather straps tight to ensure complete immobility!",
            "neutralizes their escape plan with a set of velvet ropes, tying them securely to the high-backed chair!",
            "shackles their hands to the wooden cross beam, leaving them completely exposed under the red spot light!",
            "locks a heavy metal collar around their throat, establishing absolute playground rules over their body!",
            "slams the wooden lock of the pillory shut, leaving them completely bare and surrendered to the master's will!",
            "confiscates all their personal gear, leaving them stripped, bound, and helpless on the plush velvet sofa!",
            "marks their bare back with a soft feather tickler, leaving them trembling in complete submissive release!",
            "forces them to kneel on the soft sheepskin rug, locking their wrists to their leather ankle straps!",
            "locks them in the private suspension frame, lifting them slightly off the ground into complete subspace!",
            "delivers a final, resounding spank with the spanking glove, leaving their skin warm and deep red!",
            "snaps a cold padlock onto their collar chain, handing the key to the master with a deep bow!",
            "completely wraps their torso in tight silk ropes, leaving them entirely defenseless on the leather table!",
            "neutralizes their final protest with a soft velvet blindfold, sealing their submission in darkness!",
            "claims their total playroom tribute, leaving them completely bare, bound, and breathless on the cushions!",
            "drags them to the suspension apparatus, hooking their wrist restraints to the high pulley system!",
            "neutralizes their mobility completely, locking their ankles to the heavy steel spreader bar!",
            "shackles their hands to the brass wall brackets, leaving them completely exposed under the chandelier!",
            "locks a posture collar around their neck, forcing their chin up in complete and beautiful submission!",
            "slams the heavy oak door shut, leaving them bound and blindfolded inside the private sensory booth!",
            "confiscates their final piece of clothing, leaving them standing bare and shivering under the red spotlight!",
            "marks their bare skin with a gentle, warm drop of lavender wax to seal their submissive status!",
            "forces them to lie flat on the spanking bench, securing their waist with a wide leather strap!",
            "locks them in the heavy iron wall chains, leaving them completely exposed to the master's next command!",
            "delivers a final, soft flogger strike across their shoulders, marking the end of their resistance!",
            "snaps a cold metal collar around their neck, hooking their leash to the base of the master's throne!",
            "completely binds their arms to their sides with a tight leather harness, leaving them helpless!",
            "neutralizes their final struggle with a soft silicone gag, securing their silent surrender to the room!",
            "claims their total willpower, forcing them to hold a submissive, kneeling posture on the rug!",
            "drags them by their collar leash into the private VIP playroom, locking the door behind them!",
            "neutralizes their defenses with a thick neoprene hood, cutting off their vision and voice completely!",
            "shackles their wrists to the wooden pillory frame, leaving them completely bare to the room!",
            "locks their ankles to the floor rings, forcing them to hold a wide, submissive stance on the mattress!",
            "slams the heavy iron gate shut, securing them inside the playroom cage for the duration of the night!",
            "delivers a final, stinging crop strike across their lower back, heating up their skin under the lights!",
            "forces them into a complete suspension swing, lifting them slowly off the ground into subspace!",
            "snaps heavy leather cuffs around their wrists, binding them securely to the St. Andrew's cross!",
            "completely strips away their final lace barrier, leaving them standing bare and bound under the chandelier!",
            "claims their final submission, locking their collar leash to the heavy brass ring on the pillar!",
            "drags them to the spanking horse, fastening the leather straps to ensure absolute immobility!",
            "neutralizes their escape plan with a soft velvet rope harness, tying them securely to the post!",
            "shackles their hands to the high wooden beam, leaving them completely exposed and breathless!",
            "locks a heavy metal collar around their throat, establishing absolute playground rules over their body!",
            "slams the heavy timber lock shut, leaving them completely bare and surrendered in the pillory!",
            "confiscates all their remaining pride, leaving them stripped, bound, and helpless on the fur rug!",
            "marks their bare skin with a soft fur whip, leaving them trembling in complete submissive release!",
            "forces them to kneel on the polished floor, locking their wrists to the metal rings behind them!",
            "locks them in the private suspension frame, lifting them slowly into absolute, heavy subspace!",
            "delivers a final, resounding spank with the spanking glove, leaving their skin warm and deep red!",
            "snaps a cold padlock onto their collar chain, handing the key to the master with a deep bow!",
            "completely wraps their torso in tight silk ropes, leaving them entirely defenseless on the leather table!",
            "neutralizes their final protest with a soft velvet blindfold, sealing their submission in darkness!",
            "claims their total playroom tribute, leaving them completely bare, bound, and breathless on the cushions!",
            "drags them to the suspension apparatus, hooking their wrist restraints to the high pulley system!",
            "neutralizes their mobility completely, locking their ankles to the heavy steel spreader bar!",
            "shackles their hands to the brass wall brackets, leaving them completely exposed under the chandelier!",
            "locks a posture collar around their neck, forcing their chin up in complete and beautiful submission!",
            "slams the heavy oak door shut, leaving them bound and blindfolded inside the private sensory booth!",
            "confiscates their final piece of clothing, leaving them standing bare and shivering under the red spotlight!",
            "marks their bare skin with a gentle, warm drop of lavender wax to seal their submissive status!",
            "forces them to lie flat on the spanking bench, securing their waist with a wide leather strap!",
            "locks them in the heavy iron wall chains, leaving them completely exposed to the master's next command!",
            "delivers a final, soft flogger strike across their shoulders, marking the end of their resistance!",
            "snaps a cold metal collar around their neck, hooking their leash to the base of the master's throne!",
            "completely binds their arms to their sides with a tight leather harness, leaving them helpless!",
            "neutralizes their final struggle with a soft silicone gag, securing their silent surrender to the room!",
            "claims their total willpower, forcing them to hold a submissive, kneeling posture on the rug!",
            "drags them by their collar leash into the private VIP playroom, locking the door behind them!",
            "neutralizes their defenses with a thick neoprene hood, cutting off their vision and voice completely!",
            "shackles their wrists to the wooden pillory frame, leaving them completely bare to the room!",
            "locks their ankles to the floor rings, forcing them to hold a wide, submissive stance on the mattress!",
            "slams the heavy iron gate shut, securing them inside the playroom cage for the duration of the night!",
            "delivers a final, stinging crop strike across their lower back, heating up their skin under the lights!",
            "forces them into a complete suspension swing, lifting them slowly off the ground into subspace!",
            "snaps heavy leather cuffs around their wrists, binding them securely to the St. Andrew's cross!",
            "completely strips away their final lace barrier, leaving them standing bare and bound under the chandelier!",
            "claims their final submission, locking their collar leash to the heavy brass ring on the pillar!"
        ]

        # 6. Decretos de Strip / Humilhação Extrema - Total: 107 frases
        self.humiliations: List[str] = [
            "Your resistance failed miserably. Shed every single piece of your clothing and accept your ultimate dungeon punishment.",
            "Caught red-handed and totally defenseless. Strip off your armor, show your submission, and kneel right now.",
            "No mercy for disobedient pets. Strip down completely on the cold leather mattress and expose your hot surrender.",
            "The Dominants have spoken. Hand over your pride, strip off those clothes, and bow down in complete submission.",
            "Bound in chains, bound in shame. The Master is coming, and you are caught totally bare. Start stripping!",
            "The playroom contract is signed and your body is owned. Strip down, kneel, and face your complete exposure.",
            "Your clothing is ours, your submission is ours. Take off those garments and let the chamber witness your sweet shame.",
            "The play limits are defined, and your control is gone. Strip down completely and hand over the playroom keys.",
            "You tried to rule the room, but now you serve bare. Shed your heavy gear and show your submissive posture.",
            "There is no escape from this private session. Take off every single thread of clothing and accept your penalty.",
            "Your partner cannot save you from the whip, and neither can your gear. Strip down to your bare skin right now.",
            "Underworld dungeon law is simple: losers get exposed. Strip off your clothes on this mattress and bow down.",
            "The contract is sealed in playroom ink, and your body is claimed. Strip down completely and face your Masters.",
            "Your pride has run its course. Take off those clothes, accept the collar, and kneel on the soft sheepskin rug.",
            "Shed every single piece of armor and lace. Show your complete surrender and let the playroom witness your flush.",
            "The safewords are locked away for the night. Strip down completely, accept the gag, and submit right now.",
            "No more rules, only submission. Shed your clothes on this cold asphalt floor and show your dirty secrets.",
            "Your body is owned by the house tonight. Take off those clothes, step into the cage, and accept the discipline.",
            "The whips are ready, and you are caught totally bare. Strip off those garments, kneel, and show your surrender.",
            "You have lost the playroom battle. Shed your boots, take off your clothes, and bow down to the master's chair.",
            "Your clothes are a privilege you no longer deserve. Strip down completely and show your submissive collar.",
            "The master's paddle demands your bare skin. Shed those garments, lie flat on the bench, and submit.",
            "No shelter from the flogger tonight. Take off every piece of your clothing and pay the sensory tax.",
            "Your submission must be absolute. Strip down completely on the wooden cross and let the ropes hold you.",
            "The playroom audience is watching. Shed your armor, show your blushing skin, and kneel in complete shame.",
            "Your contract is active and your clothes are ours. Take off those garments and bow down in submission.",
            "Shed every thread of lace and leather. Step onto the pedestal, show your body, and accept the collar.",
            "No more defenses, no more pride. Strip down completely on the leather couch and expose your surrender.",
            "The master's leather crop is ready. Shed those clothes, show your submission, and kneel right now.",
            "You have failed to maintain control. Strip off your garments, accept the blindfold, and submit to the playroom.",
            "Your clothes are the first barrier to be broken. Take off every piece and show your complete exposure.",
            "No mercy for disobedient toys. Strip down completely on this cold floor and face your ultimate discipline.",
            "The playroom rules are absolute. Shed your armor, show your blushing chest, and bow down in shame.",
            "Your body is the master's canvas tonight. Take off those clothes and prepare for the warm wax.",
            "The suspension harness is waiting. Strip down completely, accept the shackles, and show your surrender.",
            "You tried to resist the collar, but now you run bare. Shed your gear and kneel before the master's chair.",
            "There is no room for pride in this cell. Take off every thread of clothing and accept your submissive role.",
            "Your partner has surrendered, and so will you. Strip down to your bare skin and face your Masters.",
            "Dungeon law demands absolute exposure. Strip off your clothes on this wet mattress and bow down.",
            "The contract is signed and your body is claimed. Strip down completely and show your submissive collar.",
            "Your pride is a luxury you cannot afford. Take off those garments, accept the gag, and submit right now.",
            "Shed every piece of lace and leather. Step into the iron cage, show your body, and accept the discipline.",
            "The spanking horse is ready for its rider. Strip off your clothes, secure your ankles, and submit.",
            "No shelter from the crop tonight. Take off every piece of your clothing and pay your sensory tax.",
            "Your submission must be beautiful. Strip down completely on the wooden cross and let the ropes hold you.",
            "The master's paddle demands your bare skin. Shed those garments, lie flat on the bench, and submit.",
            "Your clothes are a barrier to your subspace. Strip down completely and show your submissive collar.",
            "No more defenses, no more pride. Strip down completely on the leather couch and expose your surrender.",
            "The master's leather crop is ready. Shed those clothes, show your submission, and kneel right now.",
            "You have failed to maintain control. Strip off your garments, accept the blindfold, and submit to the playroom.",
            "Your clothes are the first barrier to be broken. Take off every piece and show your complete exposure.",
            "No mercy for disobedient toys. Strip down completely on this cold floor and face your ultimate discipline.",
            "The playroom rules are absolute. Shed your armor, show your blushing chest, and bow down in shame.",
            "Your body is the master's canvas tonight. Take off those clothes and prepare for the warm wax.",
            "The suspension harness is waiting. Strip down completely, accept the shackles, and show your surrender.",
            "You tried to resist the collar, but now you run bare. Shed your gear and kneel before the master's chair.",
            "There is no room for pride in this cell. Take off every thread of clothing and accept your submissive role.",
            "Your partner has surrendered, and so will you. Strip down to your bare skin and face your Masters.",
            "Dungeon law demands absolute exposure. Strip off your clothes on this wet mattress and bow down.",
            "The contract is signed and your body is claimed. Strip down completely and show your submissive collar.",
            "Your pride is a luxury you cannot afford. Take off those garments, accept the gag, and submit right now.",
            "Shed every piece of lace and leather. Step into the iron cage, show your body, and accept the discipline.",
            "The spanking horse is ready for its rider. Strip off your clothes, secure your ankles, and submit.",
            "No shelter from the crop tonight. Take off every piece of your clothing and pay your sensory tax.",
            "Your submission must be beautiful. Strip down completely on the wooden cross and let the ropes hold you.",
            "The master's paddle demands your bare skin. Shed those garments, lie flat on the bench, and submit.",
            "Your clothes are a barrier to your subspace. Strip down completely and show your submissive collar.",
            "No more defenses, no more pride. Strip down completely on the leather couch and expose your surrender.",
            "The master's leather crop is ready. Shed those clothes, show your submission, and kneel right now.",
            "You have failed to maintain control. Strip off your garments, accept the blindfold, and submit to the playroom.",
            "Your clothes are the first barrier to be broken. Take off every piece and show your complete exposure.",
            "No mercy for disobedient toys. Strip down completely on this cold floor and face your ultimate discipline.",
            "The playroom rules are absolute. Shed your armor, show your blushing chest, and bow down in shame.",
            "Your body is the master's canvas tonight. Take off those clothes and prepare for the warm wax.",
            "The suspension harness is waiting. Strip down completely, accept the shackles, and show your surrender.",
            "You tried to resist the collar, but now you run bare. Shed your gear and kneel before the master's chair.",
            "There is no room for pride in this cell. Take off every thread of clothing and accept your submissive role.",
            "Your partner has surrendered, and so will you. Strip down to your bare skin and face your Masters.",
            "Dungeon law demands absolute exposure. Strip off your clothes on this wet mattress and bow down.",
            "The contract is signed and your body is claimed. Strip down completely and show your submissive collar.",
            "Your pride is a luxury you cannot afford. Take off those garments, accept the gag, and submit right now.",
            "Shed every piece of lace and leather. Step into the iron cage, show your body, and accept the discipline.",
            "The spanking horse is ready for its rider. Strip off your clothes, secure your ankles, and submit.",
            "No shelter from the crop tonight. Take off every piece of your clothing and pay your sensory tax.",
            "Your submission must be beautiful. Strip down completely on the wooden cross and let the ropes hold you.",
            "The master's paddle demands your bare skin. Shed those garments, lie flat on the bench, and submit.",
            "Your clothes are a barrier to your subspace. Strip down completely and show your submissive collar.",
            "No more defenses, no more pride. Strip down completely on the leather couch and expose your surrender.",
            "The master's leather crop is ready. Shed those clothes, show your submission, and kneel right now.",
            "You have failed to maintain control. Strip off your garments, accept the blindfold, and submit to the playroom.",
            "Your clothes are the first barrier to be broken. Take off every piece and show your complete exposure.",
            "No mercy for disobedient toys. Strip down completely on this cold floor and face your ultimate discipline.",
            "The playroom rules are absolute. Shed your armor, show your blushing chest, and bow down in shame.",
            "Your body is the master's canvas tonight. Take off those clothes and prepare for the warm wax.",
            "The suspension harness is waiting. Strip down completely, accept the shackles, and show your surrender.",
            "You tried to resist the collar, but now you run bare. Shed your gear and kneel before the master's chair.",
            "There is no room for pride in this cell. Take off every thread of clothing and accept your submissive role.",
            "Your partner has surrendered, and so will you. Strip down to your bare skin and face your Masters.",
            "Dungeon law demands absolute exposure. Strip off your clothes on this wet mattress and bow down.",
            "The contract is signed and your body is claimed. Strip down completely and show your submissive collar.",
            "Your pride is a luxury you cannot afford. Take off those garments, accept the gag, and submit right now.",
            "Shed every piece of lace and leather. Step into the iron cage, show your body, and accept the discipline.",
            "The spanking horse is ready for its rider. Strip off your clothes, secure your ankles, and submit.",
            "No shelter from the crop tonight. Take off every piece of your clothing and pay your sensory tax.",
            "Your submission must be beautiful. Strip down completely on the wooden cross and let the ropes hold you."
        ]

    def generate_fight_flavor(self, winner_name: Optional[str], loser_name: Optional[str]) -> str:
        """
        Gera uma narrativa de combate dinâmica, brutal e temática de dominação 
        combinando múltiplos elementos do léxico. Protegido contra falhas de inputs nulos.
        """
        # Proteção Fallback caso o motor passe objetos vazios por erro de carregamento do Discord
        w_name = winner_name if winner_name else "Reigning Partner"
        l_name = loser_name if loser_name else "Defeated Outlaw"

        try:
            encounter = random.choice(self.encounters).format(loser=l_name)
            attack = random.choice(self.attacks)
            defense = random.choice(self.defenses)
            evasion = random.choice(self.evasions)
            finisher = random.choice(self.finishers)
            
            narrative = (
                f"💥 **{w_name}** {encounter}\n"
                f"⚡ **{w_name}** {attack}, {defense}\n"
                f"🚨 *{evasion}*\n"
                f"👑 **{w_name}** {finisher}"
            )
            return narrative
        except Exception as e:
            logger.error(f"Failed to generate combat narrative: {e}")
            return f"💥 **{w_name}** completely overpowers **{l_name}** in a brutal showdown, claiming absolute victory!"

    def get_random_humiliation(self) -> str:
        """Retorna uma frase altamente temática de strip/humilhação do banco de dados."""
        try:
            return random.choice(self.humiliations)
        except Exception as e:
            logger.error(f"Failed to fetch random humiliation: {e}")
            return "Your heist failed. Pay the ultimate tax of complete exposure!"
